/**
 * THE ERROR VOCABULARY THAT IS ALREADY ON THE WIRE.
 *
 * ⚠️ THIS FILE ADDS A TYPE, NOT A BEHAVIOUR. Every member below was harvested from the 669
 * `NextResponse.json({ error: '…' })` returns across the 167 first-party route handlers on
 * 2026-08-06. Nothing is renamed, nothing is dropped, and no response changes by a single byte.
 * That is deliberate and it is the whole migration strategy: clients branch on these strings today
 *   src/app/messages/[id]/page.tsx      data?.error === 'human_help_pending'
 *   src/app/disputes/[id]/page.tsx      uj?.error === 'already_submitted'
 *   src/app/onboard/onboard-client.tsx  data?.error === 'phone_taken'
 *   src/components/marketplace/bulk-upload-panel.tsx  d.error === 'business_only'
 * so a rename is invisible to the compiler and breaks the UI silently. Adopting the existing
 * strings first means the type can go in with zero risk, and the tidying becomes a separate,
 * reviewable step where each rename moves the server AND its call site together.
 *
 * ⚠️ THE COLLISIONS ARE PRESERVED ON PURPOSE — they are the best argument for the type.
 *   'forbidden'    (21 sites)  vs  'Forbidden'    (16 sites)
 *   'unauthorized' ( 1 site )  vs  'Unauthorized' ( 1 site )
 * A client testing `err === 'forbidden'` is right slightly more than half the time. Both spellings
 * are listed because both are live; deleting one from the type would not delete it from the wire,
 * it would just stop TypeScript describing reality. Collapsing them is step 5 of the plan, one code
 * per commit, server and client together.
 *
 * ⚠️ THE LONG TAIL IS 165 SINGLE-USE CODES and that is a finding, not an accident of harvesting.
 * `invalid_body`, `invalid_request`, `bad_request`, `missing_fields` and twenty-six other
 * `invalid_*` variants all mean "your input was wrong". Nothing forced a choice between them, so
 * every author picked one. Listing them together is the first time that has been visible in one
 * place; consolidating is future work, and the type is what will make it safe.
 *
 * Generated by harvesting the routes, then hand-grouped. Regenerate with:
 *   git ls-files 'src/app/api/**\/route.ts' 'src/app/api/**\/route.svc.ts' | grep -v '/api/v1/' \
 *     | xargs grep -hoE "(error: '|ApiError\('|apiFail\(')[A-Za-z0-9_.-]+'" \
 *     | sed -E "s/.*'([A-Za-z0-9_.-]+)'/\1/" | sort | uniq -c
 * (three forms: the pre-wrapper `{ error: 'x' }`, and `ApiError('x')` / `apiFail('x')` from
 * `src/lib/api/handler.ts` — a migrated route emits the same string through a different shape.)
 */

/** Codes returned by three or more handlers — the shared vocabulary worth learning. */
export type SharedApiErrorCode =
  | 'auth_required'                     // 89
  | 'not_found'                         // 73
  | 'rate_limited'                      // 63
  | 'bad_request'                       // 25
  | 'forbidden'                         // 21
  | 'invalid_body'                      // 21
  | 'Forbidden'                         // 16
  | 'invalid_request'                   // 13
  | 'origin_not_allowed'                // 11
  | 'visa_encryption_not_configured'    // 10
  | 'ai_unavailable'                    // 9
  | 'not_signed_in'                     // 9
  | 'ai_failed'                         // 7
  | 'no_storefront'                     // 7
  | 'account_restricted'                // 6
  | 'business_only'                     // 6
  | 'application_locked'                // 5
  | 'empty'                             // 5
  | 'internal_error'                    // 5
  | 'application_not_deletable'         // 4
  | 'bad_origin'                        // 4
  | 'phone_taken'                       // 4
  | 'already_resolved'                  // 3
  | 'already_submitted'                 // 3
  | 'bad_body'                          // 3
  | 'bad_path'                          // 3
  | 'body_too_large'                    // 3
  | 'forum_schema_not_ready'            // 3
  | 'invalid'                           // 3
  | 'invalid_status_transition'         // 3
  | 'missing_fields'                    // 3
  | 'shop_unavailable'                  // 3
/**
 * Codes used by one or two handlers. Mostly domain-specific and legitimately narrow (`phone_taken`,
 * `window_closed`), mixed with the `invalid_*` sprawl described above.
 */
export type NicheApiErrorCode =
  | 'admin_takeover'
  | 'already_appealed'
  | 'already_generating'
  | 'already_in_use'
  | 'already_paid'
  | 'already_reviewed'
  | 'application_changed_retry'
  | 'application_delete_failed'
  | 'application_incomplete'
  | 'application_status_changed'
  | 'bad_action'
  | 'bad_avatar'
  | 'bad_id_number'
  | 'bad_phone'
  | 'bad_type'
  | 'bad_url'
  | 'bad_url_host'
  | 'banned_words'
  | 'budget_exhausted'
  | 'budget_unavailable'
  | 'business_name_required'
  | 'buyer_not_in_conversations'
  | 'cannot_block_self'
  | 'cannot_report_self'
  | 'captcha_failed'
  | 'card_superseded'
  | 'checkout_failed'
  | 'community_not_found'
  | 'complete_failed'
  | 'confirm_failed'
  | 'consent_required'
  | 'contact_in_text'
  | 'cooldown'
  | 'decode_failed'
  | 'empty_file'
  | 'failed'
  | 'file_too_large'
  | 'fx_unavailable'
  | 'geocode_failed'
  | 'id_number_required'
  | 'image_analysis_rate_limited'
  | 'image_download_failed'
  | 'image_size_invalid'
  | 'invalid_account_type'
  | 'invalid_action'
  | 'invalid_analysis_request'
  | 'invalid_block'
  | 'invalid_bookmark'
  | 'invalid_buyer'
  | 'invalid_comment'
  | 'invalid_document'
  | 'invalid_email'
  | 'invalid_events'
  | 'invalid_input'
  | 'invalid_itinerary'
  | 'invalid_kind'
  | 'invalid_locale'
  | 'invalid_media_path'
  | 'invalid_payload'
  | 'invalid_post'
  | 'invalid_report'
  | 'invalid_scopes'
  | 'invalid_signature'
  | 'invalid_subscription'
  | 'invalid_token'
  | 'invalid_trip'
  | 'invalid_visa_payload'
  | 'invalid_vote'
  | 'itinerary_limit_reached'
  | 'itinerary_schema_not_ready'
  | 'legal_address_required'
  | 'legal_name_required'
  | 'limit_reached'
  | 'listing_not_found'
  | 'listing_selection_mismatch'
  | 'migration_pending'
  | 'missing_coords'
  | 'missing_id'
  | 'missing_listing'
  | 'missing_name'
  | 'missing_report_id'
  | 'missing_token'
  | 'name_too_short'
  | 'no_active_action'
  | 'no_contact'
  | 'no_contact_in_name'
  | 'no_file'
  | 'no_id'
  | 'no_ids'
  | 'no_pending_appeal'
  | 'no_phone_in_name'
  | 'no_rows'
  | 'no_shop'
  | 'no_suggestions'
  | 'not_a_flag'
  | 'not_a_video'
  | 'not_a_visa_product'
  | 'not_actionable'
  | 'not_active'
  | 'not_configured'
  | 'not_confirmed'
  | 'not_decided'
  | 'not_negotiable'
  | 'not_paid'
  | 'not_participant'
  | 'not_transacted'
  | 'not_your_card'
  | 'own_listing'
  | 'parent_not_found'
  | 'payload_too_large'
  | 'payment_required_first'
  | 'payments_not_configured'
  | 'post_not_found_or_locked'
  | 'processing_failed'
  | 'product_entry_type_mismatch'
  | 'product_not_configured'
  | 'product_not_for_sale'
  | 'product_not_selected'
  | 'product_price_unavailable'
  | 'provider_not_configured'
  | 'question_required'
  | 'queue_failed'
  | 'quote_changed'
  | 'quote_expired'
  | 'recipient_unreachable'
  | 'reference_mismatch'
  | 'refinement_limit'
  | 'reply_required'
  | 'report_cooldown'
  | 'reporting_blocked'
  | 'retry'
  | 'save_failed'
  | 'send_failed'
  | 'send_in_flight'
  | 'sign_failed'
  | 'store_failed'
  | 'submission_window_closed'
  | 'taken'
  | 'thread_conflict'
  | 'thread_not_bound'
  | 'too_big'
  | 'too_large'
  | 'too_many'
  | 'too_many_keys'
  | 'too_many_rows'
  | 'too_many_webhooks'
  | 'too_short'
  | 'transcode_failed'
  | 'translate_timeout'
  | 'translate_unavailable'
  | 'unauthorized'
  | 'Unauthorized'
  | 'under_review'
  | 'unknown'
  | 'unknown_category'
  | 'unknown_macro'
  | 'unsafe_url'
  | 'unsupported_file_type'
  | 'unsupported_image_type'
  | 'url_required'
  | 'verification_locked'
  | 'verify_phone_to_claim'
  | 'vertex_not_configured'
  | 'visa_database_unavailable'
  | 'window_closed'
/** Every error code this API can return today. */
export type ApiErrorCode = SharedApiErrorCode | NicheApiErrorCode

/**
 * The shape every first-party handler returns on failure. Matches what the routes emit today —
 * a bare `{ error }` — rather than the richer `{ error: { code, message } }` envelope `/api/v1`
 * uses, because changing the shape is a wire change and this file is explicitly not that.
 */
export type ApiErrorBody = { error: ApiErrorCode }

/**
 * Narrow an unknown JSON body to a known error code. Use on the CLIENT, where the alternative is
 * `data?.error === 'some_string'` with no compiler involvement at all.
 *
 * Returns `null` for a body that is not a recognised error — including a code that exists on the
 * server but is missing from this file, which is the case worth thinking about: it means the
 * harvest is stale. Prefer regenerating (see the header) over adding one member by hand.
 */
export function apiErrorCode(body: unknown): ApiErrorCode | null {
  if (!body || typeof body !== 'object') return null
  const e = (body as { error?: unknown }).error
  return typeof e === 'string' && (ALL as readonly string[]).includes(e) ? (e as ApiErrorCode) : null
}

/**
 * The runtime companion to the union. Kept as a `const` array rather than duplicated by hand so the
 * type and the check cannot disagree — `satisfies` proves every entry is a member, and a code added
 * to the type but not here fails to compile.
 */
const ALL = [
  'Forbidden',
  'Unauthorized',
  'account_restricted',
  'admin_takeover',
  'ai_failed',
  'ai_unavailable',
  'already_appealed',
  'already_generating',
  'already_in_use',
  'already_paid',
  'already_resolved',
  'already_reviewed',
  'already_submitted',
  'application_changed_retry',
  'application_delete_failed',
  'application_incomplete',
  'application_locked',
  'application_not_deletable',
  'application_status_changed',
  'auth_required',
  'bad_action',
  'bad_avatar',
  'bad_body',
  'bad_id_number',
  'bad_origin',
  'bad_path',
  'bad_phone',
  'bad_request',
  'bad_type',
  'bad_url',
  'bad_url_host',
  'banned_words',
  'body_too_large',
  'budget_exhausted',
  'budget_unavailable',
  'business_name_required',
  'business_only',
  'buyer_not_in_conversations',
  'cannot_block_self',
  'cannot_report_self',
  'captcha_failed',
  'card_superseded',
  'checkout_failed',
  'community_not_found',
  'complete_failed',
  'confirm_failed',
  'consent_required',
  'contact_in_text',
  'cooldown',
  'decode_failed',
  'empty',
  'empty_file',
  'failed',
  'file_too_large',
  'forbidden',
  'forum_schema_not_ready',
  'fx_unavailable',
  'geocode_failed',
  'id_number_required',
  'image_analysis_rate_limited',
  'image_download_failed',
  'image_size_invalid',
  'internal_error',
  'invalid',
  'invalid_account_type',
  'invalid_action',
  'invalid_analysis_request',
  'invalid_block',
  'invalid_body',
  'invalid_bookmark',
  'invalid_buyer',
  'invalid_comment',
  'invalid_document',
  'invalid_email',
  'invalid_events',
  'invalid_input',
  'invalid_itinerary',
  'invalid_kind',
  'invalid_locale',
  'invalid_media_path',
  'invalid_payload',
  'invalid_post',
  'invalid_report',
  'invalid_request',
  'invalid_scopes',
  'invalid_signature',
  'invalid_status_transition',
  'invalid_subscription',
  'invalid_token',
  'invalid_trip',
  'invalid_visa_payload',
  'invalid_vote',
  'itinerary_limit_reached',
  'itinerary_schema_not_ready',
  'legal_address_required',
  'legal_name_required',
  'limit_reached',
  'listing_not_found',
  'listing_selection_mismatch',
  'migration_pending',
  'missing_coords',
  'missing_fields',
  'missing_id',
  'missing_listing',
  'missing_name',
  'missing_report_id',
  'missing_token',
  'name_too_short',
  'no_active_action',
  'no_contact',
  'no_contact_in_name',
  'no_file',
  'no_id',
  'no_ids',
  'no_pending_appeal',
  'no_phone_in_name',
  'no_rows',
  'no_shop',
  'no_storefront',
  'no_suggestions',
  'not_a_flag',
  'not_a_video',
  'not_a_visa_product',
  'not_actionable',
  'not_active',
  'not_configured',
  'not_confirmed',
  'not_decided',
  'not_found',
  'not_negotiable',
  'not_paid',
  'not_participant',
  'not_signed_in',
  'not_transacted',
  'not_your_card',
  'origin_not_allowed',
  'own_listing',
  'parent_not_found',
  'payload_too_large',
  'payment_required_first',
  'payments_not_configured',
  'phone_taken',
  'post_not_found_or_locked',
  'processing_failed',
  'product_entry_type_mismatch',
  'product_not_configured',
  'product_not_for_sale',
  'product_not_selected',
  'product_price_unavailable',
  'provider_not_configured',
  'question_required',
  'queue_failed',
  'quote_changed',
  'quote_expired',
  'rate_limited',
  'recipient_unreachable',
  'reference_mismatch',
  'refinement_limit',
  'reply_required',
  'report_cooldown',
  'reporting_blocked',
  'retry',
  'save_failed',
  'send_failed',
  'send_in_flight',
  'shop_unavailable',
  'sign_failed',
  'store_failed',
  'submission_window_closed',
  'taken',
  'thread_conflict',
  'thread_not_bound',
  'too_big',
  'too_large',
  'too_many',
  'too_many_keys',
  'too_many_rows',
  'too_many_webhooks',
  'too_short',
  'transcode_failed',
  'translate_timeout',
  'translate_unavailable',
  'unauthorized',
  'under_review',
  'unknown',
  'unknown_category',
  'unknown_macro',
  'unsafe_url',
  'unsupported_file_type',
  'unsupported_image_type',
  'url_required',
  'verification_locked',
  'verify_phone_to_claim',
  'vertex_not_configured',
  'visa_database_unavailable',
  'visa_encryption_not_configured',
  'window_closed',
] as const satisfies readonly ApiErrorCode[]

/**
 * ⚠️ `satisfies` IS ONE-DIRECTIONAL, WHICH IS NOT ENOUGH. It proves every entry of `ALL` is a member
 * of the union; it does NOT prove every member of the union appears in `ALL`. A code added to the
 * type but not the array would compile cleanly and then make `apiErrorCode()` return `null` for a
 * perfectly real error at runtime — the exact silent failure this file exists to remove. Pointed out
 * in review.
 *
 * This line closes the other direction: if any union member is missing from `ALL`, `Missing` is not
 * `never` and the assignment fails to compile, naming the absent codes in the error.
 */
type Missing = Exclude<ApiErrorCode, (typeof ALL)[number]>
const _everyCodeIsListed: Missing extends never ? true : ['missing from ALL:', Missing] = true
void _everyCodeIsListed
