import type { StoreConfig } from './partner-fetch'

/**
 * THE PARTNER SHOPS, AND WHAT WAS MEASURED TO REACH EACH ONE.
 *
 * ⛔ A TypeScript MODULE, NOT scripts/partner-stores.json — AND THE REASON IS THE DEPLOY SHAPE.
 * next.config sets `output: 'standalone'`, which traces IMPORTS to decide what ships in the
 * container. A `readFileSync(process.cwd() + '/scripts/…')` traces to nothing, so the daily cron
 * would have read a file that is not in the image and answered `partner_stores_unreadable` on
 * every run — a job that looks installed, runs nightly, and does nothing. A reviewer caught it
 * before it shipped. Imported, the list is part of the bundle by construction.
 *
 * ⚠️ EVERY `endpoint` HERE WAS PROVEN BY FETCHING TWO REAL PRODUCTS THROUGH IT. A guessed endpoint
 * that 404s is worse than an honest gap, so nothing is listed on inference — each `note` records
 * what was measured, including the ones that cost something to find.
 *
 * ⚠️ `condition` IS A CLAIM ABOUT THE GOODS, taken from that same evidence: `used` where the
 * endpoint is a used/liquidation collection, `new` for the one components retailer, and `null`
 * where the shop exposes no signal at all — which is excluded from both facet chips rather than
 * guessed. See the note on each entry.
 */
export const PARTNER_STORES: StoreConfig[] = [
  {
    "domain": "fptshop.com.vn",
    "name": "FPT Shop",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://fptshop.com.vn/products/sitemap-dien-thoai.xml",
      "https://fptshop.com.vn/products/sitemap-may-tinh-xach-tay.xml",
      "https://fptshop.com.vn/products/sitemap-may-tinh-bang.xml",
      "https://fptshop.com.vn/products/sitemap-smartwatch.xml",
      "https://fptshop.com.vn/products/sitemap-may-tinh-de-ban.xml",
      "https://fptshop.com.vn/products/sitemap-man-hinh.xml",
      "https://fptshop.com.vn/products/sitemap-linh-kien.xml",
      "https://fptshop.com.vn/products/sitemap-tivi.xml",
      "https://fptshop.com.vn/products/sitemap-camera.xml",
      "https://fptshop.com.vn/products/sitemap-thiet-bi-choi-game.xml",
      "https://fptshop.com.vn/products/sitemap-may-doc-sach.xml",
      "https://fptshop.com.vn/products/sitemap-may-in.xml",
      "https://fptshop.com.vn/products/sitemap-may-chieu.xml",
      "https://fptshop.com.vn/products/sitemap-phu-kien.xml",
      "https://fptshop.com.vn/products/sitemap-phu-kien-1.xml",
      "https://fptshop.com.vn/products/sitemap-phu-kien-2.xml",
      "https://fptshop.com.vn/products/sitemap-tu-lanh.xml",
      "https://fptshop.com.vn/products/sitemap-may-giat.xml",
      "https://fptshop.com.vn/products/sitemap-may-say-quan-ao.xml",
      "https://fptshop.com.vn/products/sitemap-tu-cham-soc-quan-ao.xml",
      "https://fptshop.com.vn/products/sitemap-may-lanh-dieu-hoa.xml",
      "https://fptshop.com.vn/products/sitemap-vat-tu-may-lanh.xml",
      "https://fptshop.com.vn/products/sitemap-quat.xml",
      "https://fptshop.com.vn/products/sitemap-quat-dieu-hoa.xml",
      "https://fptshop.com.vn/products/sitemap-dien-gia-dung.xml",
      "https://fptshop.com.vn/products/sitemap-robot-hut-bui.xml",
      "https://fptshop.com.vn/products/sitemap-may-hut-bui.xml",
      "https://fptshop.com.vn/products/sitemap-may-loc-khong-khi.xml",
      "https://fptshop.com.vn/products/sitemap-may-hut-am.xml",
      "https://fptshop.com.vn/products/sitemap-may-loc-nuoc.xml",
      "https://fptshop.com.vn/products/sitemap-may-nuoc-nong.xml",
      "https://fptshop.com.vn/products/sitemap-cay-nuoc-nong-lanh.xml",
      "https://fptshop.com.vn/products/sitemap-noi-com-dien.xml",
      "https://fptshop.com.vn/products/sitemap-thiet-bi-bep.xml",
      "https://fptshop.com.vn/products/sitemap-noi.xml",
      "https://fptshop.com.vn/products/sitemap-chao-chong-dinh.xml",
      "https://fptshop.com.vn/products/sitemap-do-dung-bep.xml",
      "https://fptshop.com.vn/products/sitemap-sinh-to-xay-ep.xml",
      "https://fptshop.com.vn/products/sitemap-do-dung-gia-dinh.xml",
      "https://fptshop.com.vn/products/sitemap-phu-kien-gia-dung.xml",
      "https://fptshop.com.vn/products/sitemap-cham-soc-suc-khoe.xml",
      "https://fptshop.com.vn/products/sitemap-smarthome.xml",
      "https://fptshop.com.vn/products/sitemap-khoa-dien-tu.xml",
      "https://fptshop.com.vn/products/sitemap-tu-dong.xml",
      "https://fptshop.com.vn/products/sitemap-tu-mat.xml",
      "https://fptshop.com.vn/products/sitemap-xe-dap.xml",
      "https://fptshop.com.vn/products/sitemap-do-choi.xml"
    ],
    "urlMatch": "^https://fptshop\\.com\\.vn/(?!products/|news/)[a-z0-9-]+/[a-z0-9.-]+$",
    "note": "Measured 2026-09-10 from the VN box, with the importer's own eno-partner-fetch UA — fptshop serves it 200 with complete JSON-LD, no bot challenge. 47 sitemaps, 6,926 product URLs, 6,926 unique slugs (no externalId collisions), and a RANDOM 24-URL sample across the whole catalogue carried a name and a price on 24 of 24 (iPhone 15 @ 21,790,000; HP EliteBook 6 G1i @ 30,990,000; Bose QC Ultra Earbuds @ 7,390,000; Nồi lẩu Sunhouse SHD4521 @ 590,000). ⛔ THE SITEMAPS MUST BE LISTED LEAF-BY-LEAF, NEVER THE INDEX. https://fptshop.com.vn/sitemap.xml is an index of 253 files of which only 48 are products; the adapter does not recurse into a sitemapindex, and a run pointed at the index would try to fetch the sitemap XML files themselves as product pages. ⛔ AND THIS IS WHY AN EARLIER PASS READ THIS SHOP AS 'NO PRICED NODE': sitemap-category.xml lists CATEGORY pages in the identical two-segment shape as products (/may-tinh-xach-tay/asus, /dien-thoai/realme, /tu-lanh/side-by-side) — a 200 with no Product node — so a sample drawn from it finds nothing, and no URL pattern can tell those from real products. Enumerating only /products/sitemap-*.xml is the discriminator. ⚠️ THE DOT IN THE urlMatch SECOND SEGMENT IS LOAD-BEARING: 29 Häfele slugs end in a dotted model number (…-t-602c-535.43.732) and [a-z0-9-]+$ drops them silently; the (?!products/|news/) lookahead guards against the index mistake above. condition 'new' is EVIDENCE, not assumption: offers.itemCondition read https://schema.org/NewCondition on 20 of 20 sampled, all InStock. ⚠️ IMAGES ARE FIVE BUT NOT FIVE ANGLES — the JSON-LD carries exactly one image and galleryFrom's slug-token filter fills to 5, except fptshop's CDN serves one source file at several widths (1920x0 and 750x0 of the same .png), so expect ~4 genuinely distinct photos. ⚠️ SITEMAP ORDER DECIDES WHAT A LIMITED RUN TAKES (readProductPages slices the first LIMIT of the insertion-ordered set), so the phones/laptops files are listed FIRST here rather than in the site's own index order, which begins with software. /products/sitemap-phan-mem.xml IS DELIBERATELY OMITTED — its 40 entries are Microsoft 365 and Defender subscriptions, not shippable goods. ⚠️ THE OWNER'S LINK, /may-doi-tra, IS NOT THIS SOURCE and is not reachable from it: the used/trade-in hub's products sit one level deeper (/may-doi-tra/dien-thoai-cu-gia-re/<slug>) and appear in NO sitemap. They do carry priced JSON-LD (iPhone 17 Pro 256GB Demo @ 28,920,888; OPPO A6T Demo @ 4,422,600; Honor X7d Demo @ 4,383,396), but each of the 10 collections renders at most 24 links and ?page=2 returns byte-identical links to page 1 while /page-2/ 404s — a ceiling of ~190 products — and their JSON-LD image is an EMPTY STRING, so a collection-crawl entry there would recover about one photo each. Left out on purpose; owner said 'add all used new doesnt matter' and the sitemap catalogue already carries 6,926. ⚠️ At the 1200ms politeness gap a full unlimited run is ~2.3 hours of requests against one host.",
    "condition": "new"
  },
  {
    "domain": "dienmaycholon.com",
    "name": "Siêu Thị Điện Máy - Nội Thất Chợ Lớn",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://dienmaycholon.com/sitemap/sitemap_may_giat.xml",
      "https://dienmaycholon.com/sitemap/sitemap_tivi.xml",
      "https://dienmaycholon.com/sitemap/sitemap_noi_com_dien.xml",
      "https://dienmaycholon.com/sitemap/sitemap_dien_thoai_di_dong.xml",
      "https://dienmaycholon.com/sitemap/sitemap_tu_lanh.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa_keo.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa.xml",
      "https://dienmaycholon.com/sitemap/sitemap_amply_dau_dia_than.xml",
      "https://dienmaycholon.com/sitemap/sitemap_micro.xml",
      "https://dienmaycholon.com/sitemap/sitemap_phu_kien_dien_tu.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_lanh.xml",
      "https://dienmaycholon.com/sitemap/sitemap_tu_dong.xml",
      "https://dienmaycholon.com/sitemap/sitemap_tu_mat.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_nuoc_nong.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_say.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_nong_lanh.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_loc_khong_khi.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_rua_chen_say_chen.xml",
      "https://dienmaycholon.com/sitemap/sitemap_laptop_macbook.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_tinh_bang.xml",
      "https://dienmaycholon.com/sitemap/sitemap_phu_kien_di_dong.xml",
      "https://dienmaycholon.com/sitemap/sitemap_lo_vi_song.xml",
      "https://dienmaycholon.com/sitemap/sitemap_bep_ga_duong_am.xml",
      "https://dienmaycholon.com/sitemap/sitemap_bep_tu_hong_ngoai.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_hut_mui_hut_khoi.xml",
      "https://dienmaycholon.com/sitemap/sitemap_noi_ap_suat.xml",
      "https://dienmaycholon.com/sitemap/sitemap_noi_lau_dien.xml",
      "https://dienmaycholon.com/sitemap/sitemap_am_ca_binh_dun.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_xay_sinh_to.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_ep_trai_cay.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_lam_sua_hat.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_pha_ca_phe.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_hut_bui_robot_hut_bui.xml",
      "https://dienmaycholon.com/sitemap/sitemap_ban_ui.xml",
      "https://dienmaycholon.com/sitemap/sitemap_quat.xml",
      "https://dienmaycholon.com/sitemap/sitemap_say_toc.xml",
      "https://dienmaycholon.com/sitemap/sitemap_do_dung_nha_bep.xml",
      "https://dienmaycholon.com/sitemap/sitemap_do_dung_gia_dinh.xml",
      "https://dienmaycholon.com/sitemap/sitemap_thiet_bi_chieu_sang.xml",
      "https://dienmaycholon.com/sitemap/sitemap_noi_chao.xml",
      "https://dienmaycholon.com/sitemap/sitemap_binh_thuy_dien.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_loc_nuoc.xml",
      "https://dienmaycholon.com/sitemap/sitemap_phu_kien.xml",
      "https://dienmaycholon.com/sitemap/sitemap_tu_uop_ruou.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa_bluetooth.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa_thanh_soundbar.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_lam_mat_quat_dieu_hoa.xml",
      "https://dienmaycholon.com/sitemap/sitemap_noi_chien_noi_nuong.xml",
      "https://dienmaycholon.com/sitemap/sitemap_can_suc_khoe.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_say_trai_cay.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa_vi_tinh.xml",
      "https://dienmaycholon.com/sitemap/sitemap_lo_nuong.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_xay_thit.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_danh_trung.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_vat_cam.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_xit_rua.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_do_huyet_ap.xml",
      "https://dienmaycholon.com/sitemap/sitemap_ghe_massage.xml",
      "https://dienmaycholon.com/sitemap/sitemap_binh_loc_nuoc.xml",
      "https://dienmaycholon.com/sitemap/sitemap_tai_nghe.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_chieu.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa_karaoke_xach_tay.xml",
      "https://dienmaycholon.com/sitemap/sitemap_on_ap.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_lam_toi_den.xml",
      "https://dienmaycholon.com/sitemap/sitemap_khoa_dien_tu.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_cao_rau.xml",
      "https://dienmaycholon.com/sitemap/sitemap_dung_cu_gia_dinh.xml",
      "https://dienmaycholon.com/sitemap/sitemap_o_cam_dien.xml",
      "https://dienmaycholon.com/sitemap/sitemap_binh_ly_giu_nhiet.xml",
      "https://dienmaycholon.com/sitemap/sitemap_game_playstation.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa_cao_cap.xml",
      "https://dienmaycholon.com/sitemap/sitemap_dong_ho_thong_minh.xml",
      "https://dienmaycholon.com/sitemap/sitemap_thiet_bi_suoi_am.xml",
      "https://dienmaycholon.com/sitemap/sitemap_camera.xml",
      "https://dienmaycholon.com/sitemap/sitemap_loa_karaoke_mini.xml",
      "https://dienmaycholon.com/sitemap/sitemap_micro_thu_am.xml",
      "https://dienmaycholon.com/sitemap/sitemap_noi_nau_cham.xml",
      "https://dienmaycholon.com/sitemap/sitemap_den_nang_luong_mat_troi.xml",
      "https://dienmaycholon.com/sitemap/sitemap_may_bom_nuoc.xml",
      "https://dienmaycholon.com/sitemap/sitemap_noi_hap.xml"
    ],
    "urlMatch": "^https://dienmaycholon\\.com/(?!tin-khuyen-mai/)[a-z0-9-]+/[a-z0-9-]+$",
    "note": "⛔ THE 80 SITEMAPS ARE LISTED INDIVIDUALLY BECAUSE fetchSitemapJsonLd DOES NOT RECURSE INTO A SITEMAPINDEX. /sitemap.xml is an INDEX of 230 files; handing it over would enqueue those 230 .xml URLs as products, every one would yield no Product JSON-LD, and the whole shop would read as a failed run. Of the 230: 146 are KNMS_* blog/advice, 3 are category/filter/manufacturer, and sitemap_khuyenmai.xml is promo NEWS — the remaining 80 are products. All 80 verified HTTP 200 to the honest UA on 2026-09-10 (a single non-200 sets log.fatal). ⛔ sitemap_khuyenmai.xml IS DELIBERATELY OMITTED: all 428 of its URLs are /tin-khuyen-mai/ articles with no Product JSON-LD, and they were exactly the misses that made a first sample read 6.7% failed — above MAX_READ_FAILURE_RATE, which would have disabled retirement for this shop every night. Dropping it took 16,321 URLs → 15,893 and the sampled failure rate to 0/20. urlMatch re-excludes them as belt-and-braces; validated to match 15,893/15,893 products and 0/428 promo. ⚠️ MEASURED 2026-09-10 with the eno-partner-fetch UA itself, not a browser UA: 20 of 20 random products parsed a Product node and carried a price > 0 — e.g. 'Smart Tivi Samsung QLED 4K Vision AI 65 Inch QA65Q7FA' @ 10,190,000 (cross-checked against the '10.190.000 đ' rendered in the page body, so the JSON-LD price is the sell price and not an instalment or deposit figure), 'Xiaomi Redmi Note 15 5G (6GB+128GB)' @ 5,990,000, 'Bàn Ủi Hơi Nước Đứng Panasonic NI-GSG060WRA' @ 2,190,000. ⚠️ EVERY URL IS /<category>/<slug> AND SLUG COLLISIONS ARE ZERO across all 16,321 — counted, not assumed — so the URL-slug externalId is safe here (this is the check laptoptrunghau.com failed). Images: JSON-LD carries ONE image, galleryFrom recovers 5/5; note the gallery CDN is cdn11.dienmaycholon.vn — a different TLD from the site — which works only because galleryFrom derives its registrable-domain root from the JSON-LD seed image rather than from cfg.domain. condition 'new' is the shop's own claim, not an inference: 12 of 12 sampled pages emit itemCondition NewCondition, and there is no used channel to point at — /may-doi-tra, /hang-trung-bay, /hang-cu and /thanh-ly all soft-404. ⚠️ ~15-32% of these are InStock; the sitemaps carry a deep tail of discontinued models (2014 Samsung plasmas), which import as status 'sold' rather than being dropped. ⚠️ COST: 15,893 pages × 1,200ms ≈ 5.3 HOURS and ~4GB per full read — by far the largest shop here. If the daily cron cannot absorb that, give this shop its own schedule or a smaller but STABLE sitemap subset; never a --limit, which marks the unread tail absent.",
    "condition": "new"
  },
  {
    "domain": "thegioididong.com",
    "name": "Thế Giới Di Động",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-1?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-2?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-3?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-4?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-5?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-6?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-7?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-8?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-9?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-10?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-11?page=12",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=1",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=2",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=3",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=4",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=5",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=6",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=7",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=8",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=9",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=10",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=11",
      "https://www.thegioididong.com/newsitemap/sitemap-product-2026-12?page=12"
    ],
    "urlMatch": "^https://www\\.thegioididong\\.com/[a-z0-9-]+/[a-z0-9-]+$",
    "note": "MWG's retail catalogue, measured 2026-09-10 from the VN box. ⚠️ /sitemap.xml 404s on BOTH apex and www — the real entry point is in robots.txt: /newsitemap/sitemap-product, a 263-entry sitemap INDEX whose children are already page-split (?page=1..n, 50 URLs each). ⛔ fetchSitemapJsonLd DOES NOT FOLLOW AN INDEX, so the pages are listed explicitly here; pointing it at the index instead yields 263 sitemap URLs that urlMatch drops and zero products. Scoped to 2026 = 3,063 unique product URLs (3,052 match urlMatch; the other 11 are malformed double-slash entries); the whole index is ~12,000. ✅ An out-of-range ?page and a month that does not exist BOTH return HTTP 200 with an EMPTY <urlset>, never a 404, so the 12-page-per-month headroom costs one polite request each and never sets log.fatal — extend by adding months, not by guessing. ⚠️ Any UNKNOWN /newsitemap/* path returns the INDEX rather than a 404 (sitemap-product-all, sitemap-products, and the month URL WITHOUT ?page all did) — urlMatch is what keeps those out. Evidence: 20 of 20 randomly sampled products carried a Product JSON-LD block with a positive VND price and an og:image; 0 no-price, 0 no-LD, 0 fetch failures; 0 duplicate slugs across 3,063 URLs. ⚠️ THE USED SECTION IS NOT REACHABLE: /may-doi-tra (owner's link) appears in ZERO of the 3,063 sitemap URLs, and its listing pages — like every TGDD category page, /dtdd included — are Nuxt CLIENT-rendered: the 1.7MB server HTML contains category links only, zero product anchors, so collection-crawl finds nothing. condition 'new' is the sitemap's own evidence (it excludes the may-doi-tra used stock). ⚠️ ONE IMAGE PER PRODUCT TODAY, and it is an adapter gap, not the shop's: TGDD's JSON-LD image is an ImageObject keyed contentUrl, while imagesFrom reads only .url — the seed comes back empty, galleryFrom returns before the gallery harvest, and only og:image survives. Measured with contentUrl accepted as the seed: 5 / 5 / 3 images on the Philips TAT3120, Galaxy S25 Ultra and Casio MTP-VT06L pages. ⚠️ ~3,063 pages x 1.2s ≈ 62 minutes per full pass, plus ~3 minutes to walk the 144 sitemaps.",
    "condition": "new"
  },
  {
    "domain": "bachlongstore.vn",
    "name": "Bạch Long Store",
    "city": "Hồ Chí Minh",
    "adapter": "collection-crawl",
    "endpoint": "",
    "collections": [
      "https://bachlongstore.vn/san-pham.html"
    ],
    "pageParam": "/?p={n}",
    "maxPages": 130,
    "urlMatch": "^https://bachlongstore\\.vn/.+\\.html$",
    "htmlPrice": "id=['\\\"]ext_price['\\\"][^>]*>\\s*([0-9.,]+)",
    "idFrom": "path",
    "note": "Custom PHP CMS (vnt_*), no product feed: /products.json and the Woo Store API both 404. ⛔ THE PRODUCT JSON-LD CARRIES NO `offers` — measured on 15 product pages, the node has name/description/url/brand and nothing else, and `image` is the empty string. The price is HTML-only, in `id=\"ext_price\"`, and ⚠️ THE QUOTE STYLE VARIES PER PAGE (`id='ext_price'` is live on real pages, e.g. the MacBook Pro 14 M1 Pro at 22,750,000 đ), so a double-quote-only regex reads a priced product as unpriced. Without an ext_price fallback in readProductPages this shop imports ZERO products. \"Liên hệ\" renders in the same node and parses to 0, which the existing price>0 filter drops correctly (1 of 15 sampled). ⛔ externalId CANNOT BE THE LAST PATH SEGMENT HERE: 298 of 2,517 product URLs put the spec string in a path segment (/samsung-galaxy-z-fold7-12gb/512gb-cu.html), and split('/').pop() collides 38 ways across 169 products (`a-pin-100.html` ×12, `512gb.html` ×12, `256gb-cu.html` ×11) — enough to trip the collision guard, drop those rows and mark every read INCOMPLETE for ever. The full path after the host collides 0 times over all 2,517. ⚠️ NOT sitemap-jsonld even though a 4,781-URL sitemap exists: only ~37% of it is products (sampled 40, found 15), the rest is blog articles and category pages with no Product JSON-LD and no metadata distinguishing them — every one would count as a failed read. /san-pham.html is the shop's own global all-products listing, 20 per page, 126 pages, and paging all of it yielded exactly 2,517 distinct products. ⚠️ Past page 126 the theme serves the LAST page's markup at HTTP 200 (verified at ?p=127 and ?p=200), so termination depends on the no-new-URLs rule, not on an empty page. ⚠️ ONE PHOTO PER PRODUCT, served as three thumb sizes of one file; og:image is the cover and the gallery harvest will add nothing (numeric filenames share no slug tokens). ⚠️ CONDITION IS UNCLAIMED: used and new are mixed and the only signal is words in the title (\"cũ\", \"99%\", \"PIN 95%\" vs \"Chính hãng\"), which is not machine-readable — and the owner's instruction was \"add all used new doesnt matter\". Prices proven on 14 different products, e.g. 'Apple iPhone 14 Pro 256GB cũ' @ 13,950,000, 'Xiaomi Redmi 15 4G (6GB-128GB)' @ 4,850,000, 'LOA BLUETOOTH BOSE HOME SPEAKER 500' @ 9,900,000.",
    "condition": null
  },
  {
    "domain": "dienthoaigiakho.vn",
    "name": "Điện Thoại Giá Kho",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://dienthoaigiakho.vn/sitemap.xml"
    ],
    "urlMatch": "^https://dienthoaigiakho\\.vn/[a-z0-9-]+-[0-9]{9,}$",
    "note": "⚠️ A NEXT.JS SPA THAT IS STILL READABLE — the collection pages are client-rendered (pages router, buildId in /_next/static/<id>/) and carry no product links, but the SITEMAP is a flat urlset of 1,163 URLs and every PRODUCT page server-renders bare-`Product` JSON-LD with offers.price in whole VND. 12 of 12 randomly sampled products carried a price (0 failures) using the importer's own eno-partner-fetch UA, which this shop does not block. ⛔ DO NOT REACH FOR collection-crawl HERE: the /_next/data/<buildId>/<category>.json route looks paginable but IGNORES ?page= — page=2 and page=3 return byte-identical page-1 payloads — and the summed category counts (430) are half what the sitemap lists. ⚠️ THE urlMatch IS THE WHOLE FILTER: product slugs end in a 10-digit unix-ms id (…-1780284027) which is also the shop's sku, and that trailing-digits rule is what separates the 864 products from 299 category/static pages (/cart, /pages/*, /dong-ho/apple-watch/series-11) in the SAME flat sitemap. ⛔ THERE IS AN OPEN WOOCOMMERCE STORE API AND IT IS THE WRONG SOURCE: /tin-cong-nghe/wp-json/wc/store/v1/products serves 875 priced products in 9 requests, but every row is type 'external' whose permalink is the robots-Disallowed WP affiliate mirror (/tin-cong-nghe/san-pham/…); the canonical URL exists only in that mirror page's cart-form action, not in the API JSON, so importing it would send every buyer to the wrong page. Keep it as a cheap census for reconciliation, not as the read. ⚠️ Gallery harvest is uneven: galleryFrom's ≥2-shared-slug-token rule finds 9–15 images on phones/tablets/watches but 0 on small accessories, which land with the JSON-LD cover alone. CONDITION IS UNCLAIMED — the catalogue openly mixes 'Chính Hãng' (new), 'Likenew Fullbox' and 'Cũ 99%' in one feed with no machine-readable condition field, and the owner's instruction was \"add all used new doesnt matter\", so the whole catalogue is taken and no claim is made about the goods.",
    "condition": null
  },
  {
    "domain": "daitailoc.com",
    "name": "Đại Tài Lộc",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": ["https://daitailoc.com/sitemap-products.xml"],
    "urlMatch": "^https://daitailoc\\.com/[a-z0-9-]+$",
    "note": "⚠️ CONDITION IS UNCLAIMED: the evidence here is prices and JSON-LD, not condition — nothing on these pages says used, and the owner's instruction was \"add all used new doesnt matter\", so no claim is made about the goods. ⛔ THIS SHOP WAS WRONGLY WRITTEN OFF AS 'NO PRICES'. An earlier pass sampled 14 products and found a price on none of them — the real cause was findProductNode comparing `@type` against the bare string 'Product' while these pages publish the FULLY-QUALIFIED `http://schema.org/Product`. With that fixed, 4 of 5 sampled carry a price (e.g. 'Màn hình máy tính LCD VSP V2408S' @ 1,850,000). 4,642 URLs in its own sitemap-products.xml; a stale one 404s here and there, which counts as a failed read rather than a delisting.",
    "condition": null
  },
  {
    "domain": "hoanghamobile.com",
    "name": "Hoàng Hà Mobile",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": ["https://hoanghamobile.com/sitemap.xml"],
    "urlMatch": "^https://hoanghamobile\\.com/[a-z0-9-]+/[a-z0-9-]+",
    "note": "One flat sitemap, 9,608 URLs, 4 of 5 sampled carry a JSON-LD price. ⚠️ DO NOT FILTER THIS SHOP ON 'cu' — `/cu-sac-day-cap` is 'củ sạc' (a CHARGER), not 'cũ' (used), and a used-only regex matched 251 charger and cable categories while missing the actual stock. Owner, 2026-09-10: \"add all used new doesnt matter\", so the whole catalogue is taken and the condition is left unclaimed.",
    "condition": null
  },
  {
    "domain": "laptoptrunghau.com",
    "name": "Laptop Trung Hậu",
    "city": "Hồ Chí Minh",
    "adapter": "collection-crawl",
    "endpoint": "",
    "collections": [
      "https://laptoptrunghau.com/laptop-cu.htm",
      "https://laptoptrunghau.com/laptop-acer-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-asus-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-dell-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-hp-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-lenovo-ibm-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-msi-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-panasonic-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-samsung-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-sony-vaio-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-surface-cu-gia-re.htm",
      "https://laptoptrunghau.com/laptop-toshiba-cu-gia-re.htm",
      "https://laptoptrunghau.com/macbook-cu-gia-re.htm"
    ],
    "urlMatch": "^https://laptoptrunghau\\.com/[a-z0-9-]+\\.htm$",
    "maxPages": 1,
    "note": "The whole shop is used laptops, and it publishes 13 brand collections under /laptop-cu.htm — all of them are listed because the crawler does not recurse. ⚠️ maxPages 1: the collections carry NO pagination links at all, so asking for page 2 just refetches page 1. ⛔ PRODUCTS AND CATEGORIES SHARE ONE URL SHAPE (both are /<slug>.htm at depth 1) and cannot be told apart by the URL — the JSON-LD check does it instead: a category page has no Product node and drops out, exactly as zshop's about page does. Verified 3 of 4 sampled products carry a price (ASUS X441UVK @ 5,200,000).",
    "condition": "used"
  },
  {
    "domain": "zshop.vn",
    "name": "ZShop",
    "city": "Hồ Chí Minh",
    "adapter": "collection-crawl",
    "endpoint": "",
    "collections": ["https://zshop.vn/kho-hang-cu/"],
    "pageParam": "/page-{n}/",
    "urlMatch": "^https://zshop\\.vn/[a-z0-9-]+\\.html$",
    "note": "The owner's own link: /kho-hang-cu/ is the used warehouse. ⚠️ PAGINATION IS PATH-BASED (/kho-hang-cu/page-2/), not a query string — the default ?page={n} returns page 1 forever, which reads as a shop with 20 products. ⛔ PRODUCTS END IN .html AND CATEGORIES END IN /, which is the only reliable discriminator here: depth alone matches 210 links of which most are category pages. Measured 2026-09-10: 109 product URLs over the first 3 pages; of 6 real products sampled, 4 carry a JSON-LD price (12.99M, 30.99M, 34.99M, 7.5M) and the rest are sold — the importer drops those. Two of the eight sampled .html URLs were an about page and a profile page; they have no Product node and fall out on their own.",
    "condition": "used"
  },
  {
    "domain": "dienmaysaigon.com",
    "name": "Điện Máy Sài Gòn",
    "city": "Hồ Chí Minh",
    "adapter": "woocommerce",
    "endpoint": "https://dienmaysaigon.com/wp-json/wc/store/v1/products?category=2572&per_page=100&page={page}",
    "note": "category 2572 = 'Sản phẩm đã qua sử dụng', the used section the owner's URL (/hang-thanh-ly-hang-da-qua-su-dung/) points at. Woo's tax_query includes descendants, so the children come with it — 7573 Máy Giặt Thanh Lý, 7574 Máy Lạnh Thanh Lý, 8298 Tivi cũ. X-WP-Total 79, and the page returns all 79. Measured 2026-09-10: 6-12 images per product and real prices, though at least one row prices at 0 (a 55\" LG) which feedPrice refuses — that is the guard working, not a gap.",
    "condition": "used"
  },
  {
    "domain": "phuongtin.vn",
    "name": "Phương Tín",
    "city": "Hồ Chí Minh",
    "adapter": "woocommerce",
    "endpoint": "https://phuongtin.vn/wp-json/wc/store/v1/products?category=808&per_page=100&page={page}",
    "note": "category 808 = Laptop Cũ. Woo's tax_query includes descendants, so the brand children (809 Dell Cũ, 810 HP Cũ …) come with it. ~183 used laptops.",
    "condition": "used"
  },
  {
    "domain": "thegioiso365.vn",
    "name": "Thế Giới Số 365",
    "city": "Hồ Chí Minh",
    "adapter": "woocommerce",
    "endpoint": "https://thegioiso365.vn/wp-json/wc/store/v1/products?category=98&per_page=100&page={page}",
    "note": "category 98 = Laptop Like New, whole brand subtree. X-WP-Total 486 — larger than the term's own count=393 because the filter rolls in children; 486 is what the endpoint actually returns.",
    "condition": "used"
  },
  {
    "domain": "tystore.vn",
    "name": "Ty Store",
    "city": "Hồ Chí Minh",
    "adapter": "woocommerce",
    "endpoint": "https://tystore.vn/wp-json/wc/store/v1/products?category=17,21,25,27&per_page=100&page={page}",
    "note": "the four top-level Cũ terms: 17 iPhone, 21 iPad, 25 MacBook, 27 iMac. 68 used of 188 site-wide.",
    "condition": "used"
  },
  {
    "domain": "tuannguyenmobile.com",
    "name": "Tuấn Nguyễn Mobile",
    "city": "Hồ Chí Minh",
    "adapter": "woocommerce",
    "endpoint": "https://tuannguyenmobile.com/wp-json/wc/store/v1/products?category=66,178,187,198,245,246,248,250,283,286,306,314,335,338,341&per_page=100&page={page}",
    "note": "15 root-level used/liquidation terms (iPhone Cũ, iPad Cũ, Apple Watch cũ, PlayStation Cũ, Laptop Cũ, Macbook Cũ, Máy Ảnh Cũ, Samsung Cũ …). 489 of the shop's 504.",
    "condition": "used"
  },
  {
    "domain": "banghethanhly.vn",
    "name": "Bàn Ghế Thanh Lý",
    "city": "Hồ Chí Minh",
    "adapter": "woocommerce",
    "endpoint": "https://banghethanhly.vn/wp-json/wc/store/v1/products?category=16,17,18,19,20,21,22,23,198,210,211,219,221,222&per_page=100&page={page}",
    "note": "⚠️ THE FILTER IS AN EXCLUSION, NOT AN INCLUSION. The whole shop is liquidation stock, so the useful question is not 'which category is used' but 'which is already SOLD' — category 15 'Đã bán' holds 7,286 of the 11,124. These 14 ids are everything else: 3,764 still available. robots.txt Disallows ?sort= and ?order=; this importer sends neither.",
    "condition": "used"
  },
  {
    "domain": "laptopgiare.vn",
    "name": "Laptop Giá Rẻ",
    "city": "Hồ Chí Minh",
    "adapter": "woocommerce",
    "endpoint": "https://laptopgiare.vn/wp-json/wc/store/products?per_page=100&page={page}",
    "note": "⚠️ NO used signal exists here — all 23 categories are brand/form-factor only, so the whole 101-product catalogue is pulled (23 in stock). Note the path is /wc/store/products, NOT /wc/store/v1/products. ⛔ condition:null DELIBERATELY — the endpoint carries no used/new signal, so asserting either on a marketplace would be a claim about the goods that nothing here supports. A null condition is excluded from BOTH facet chips, which is the honest answer.",
    "condition": null
  },
  {
    "domain": "digiphone.vn",
    "name": "Digiphone",
    "city": "Hồ Chí Minh",
    "adapter": "haravan",
    "endpoint": "https://digiphone.vn/collections/hang-cu/products.json?limit=250&page={page}",
    "note": "⚠️ EXPECT ~45% YIELD, NOT 178. Collection `hang-cu` holds 178 used phones/tablets, but 55% of fetched rows price every variant at \"0\", which the shop's own PDP renders as 'Liên hệ' (call for price). Those are skipped — a 0 price renders as 'Free / Miễn phí' on a card.",
    "condition": "used"
  },
  {
    "domain": "vnlaptop.vn",
    "name": "VN Laptop",
    "city": "Hồ Chí Minh",
    "adapter": "haravan",
    "endpoint": "https://vnlaptop.vn/collections/laptop/products.json?limit=250&page={page}",
    "note": "⚠️ NO used flag exists — all 61 collections enumerated, none carries a cũ/hàng-cũ cue — so this is the whole 113-machine catalogue rather than a used subset. ⛔ condition:null DELIBERATELY — the endpoint carries no used/new signal, so asserting either on a marketplace would be a claim about the goods that nothing here supports. A null condition is excluded from BOTH facet chips, which is the honest answer.",
    "condition": null
  },
  {
    "domain": "hshop.vn",
    "name": "HShop",
    "city": "Hồ Chí Minh",
    "adapter": "sapo",
    "endpoint": "https://hshop.vn/collections/all/products.json?limit=250&page={page}",
    "note": "⚠️ CARRIES NO USED STOCK AT ALL — all 85 collections enumerated, not one has a cũ/thanh lý/like new cue; it is an Arduino/components retailer. Included only because the owner asked for full catalogues (~1,090 products).",
    "condition": "new"
  },
  {
    "domain": "minhtuanmobile.com",
    "name": "Minh Tuấn Mobile",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://minhtuanmobile.com/sitemap-hang-cu-apple.xml/",
      "https://minhtuanmobile.com/sitemap-hang-cu-other.xml/"
    ],
    "urlMatch": "^https://minhtuanmobile\\.com/(?!sitemap)[^/]+/?$",
    "note": "⚠️ THE TRAILING SLASH ON THE SITEMAP URL IS REQUIRED — without it the server 301s. The shop publishes DEDICATED used sitemaps (hang-cu-apple + hang-cu-other) separate from its new-stock ones, so the used set needs no keyword guessing: 373 Apple + the other file. ⚠️ Product URLs carry a TRAILING SLASH (/iphone-x-cu-dep/) — a [^/]+$ pattern matches none of them.",
    "condition": "used"
  },
  {
    "domain": "mayanh24h.com",
    "name": "Máy Ảnh 24h",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://mayanh24h.com/sitemap/product/sitemap1.xml",
      "https://mayanh24h.com/sitemap/product/sitemap2.xml",
      "https://mayanh24h.com/sitemap/product/sitemap3.xml",
      "https://mayanh24h.com/sitemap/product/sitemap4.xml",
      "https://mayanh24h.com/sitemap/product/sitemap5.xml",
      "https://mayanh24h.com/sitemap/product/sitemap6.xml"
    ],
    "urlMatch": "-cu$",
    "note": "⚠️ PRODUCT URLs ARE EXTENSIONLESS — https://mayanh24h.com/canon-650d-cu, not .html. A '-cu\\.html$' filter matched 0 of 1,004. Used stock is the '-cu' slug suffix: 144 in file 1, ~850 across all six. The 6 /product/sitemapN.xml paths advertised in robots.txt 404; these come from the /sitemap/sitemap2.xml index. robots.txt blocks ?page= so category pages are not used for discovery.",
    "condition": "used"
  },
  {
    "domain": "didongviet.vn",
    "name": "Di Động Việt",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://didongviet.vn/product-sitemap1.xml",
      "https://didongviet.vn/product-sitemap2.xml",
      "https://didongviet.vn/product-sitemap3.xml",
      "https://didongviet.vn/product-sitemap4.xml",
      "https://didongviet.vn/product-sitemap5.xml",
      "https://didongviet.vn/product-sitemap6.xml",
      "https://didongviet.vn/product-sitemap7.xml",
      "https://didongviet.vn/product-sitemap8.xml",
      "https://didongviet.vn/product-sitemap9.xml",
      "https://didongviet.vn/product-sitemap10.xml",
      "https://didongviet.vn/product-sitemap11.xml",
      "https://didongviet.vn/product-sitemap12.xml",
      "https://didongviet.vn/product-sitemap13.xml",
      "https://didongviet.vn/product-sitemap14.xml",
      "https://didongviet.vn/product-sitemap15.xml",
      "https://didongviet.vn/product-sitemap16.xml"
    ],
    "urlMatch": "/may-cu-gia-re/",
    "note": "Used stock lives under one exclusive path prefix, /may-cu-gia-re/ — measured across two 500-URL sitemaps with zero used-looking URLs outside it, so the prefix is both complete and exclusive.",
    "condition": "used"
  },
  {
    "domain": "24hstore.vn",
    "name": "24hStore",
    "city": "Hồ Chí Minh",
    "adapter": "sitemap-jsonld",
    "endpoint": "",
    "sitemaps": [
      "https://24hstore.vn/sitemap_products.xml"
    ],
    "urlMatch": "-cu(-\\d+)?-p\\d+$|-cu/",
    "note": "One flat 1.5 MB sitemap, 5,247 product URLs. Used candidates by slug suffix '-cu…-p<id>' OR a category segment ending '-cu': 498 of them. The /hang-cu landing page renders only 130 cards — a merchandised subset, not the catalogue.",
    "condition": "used"
  }
]
