/**
 * THE SEAL FILES ARE COUPLED TO THE COMPONENT, AND THIS IS THE COUPLING.
 *
 * public/seal.svg, seal-line.svg and seal-white.svg are generated by
 * scripts/gen-seal-svg.mjs from the three paths eno-seal.tsx exports. Nothing at runtime
 * re-derives them: they are bytes on disk, so the ONLY thing standing between "someone
 * nudged SEAL_CHECK" and "the marketplace serves two different seals" is a test that
 * regenerates and compares. A seal that drifts is a counterfeit (docs/icon-language.md
 * §0b), and a counterfeit that ships silently is worse than a build failure.
 *
 * ⚠️ THE ASSERTIONS ARE DELIBERATELY DOUBLED, AND THAT IS NOT PADDING. The generator finds
 * the paths by pattern-matching the component's source, so a test that only compared
 * "generator output" with "generator output on disk" would agree with itself even if the
 * parser had started returning the wrong strings entirely. So the paths are ALSO imported
 * as live values from the component and asserted to appear verbatim in every file: one
 * check catches a stale file, the other catches a broken parser, and neither can cover for
 * the other.
 *
 * Failure here is never "fix the test" — it is `node scripts/gen-seal-svg.mjs`.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { SEAL_CHECK, SEAL_CHIEF, SEAL_OUTLINE } from '@/components/marketplace/eno-seal'
import { STROKE_UI, WASH } from '@/lib/icon-tokens'
import {
  ROOT,
  SEAL_FILES,
  assertPathData,
  collectSealSpec,
  readRootToken,
  readSealSources,
  readStrokeTreatment,
  renderAllSeals,
  stripComments,
  washVariable,
} from '../../scripts/gen-seal-svg.mjs'

const REGENERATE = 'run `node scripts/gen-seal-svg.mjs`'
const variants = Object.keys(SEAL_FILES)

/**
 * ⚠️ LAZY, BECAUSE A THROW AT MODULE SCOPE IS A COLLECTION ERROR, NOT A TEST FAILURE.
 * Reading and parsing the sources eagerly meant a drifted component aborted the file before
 * a single `it()` ran — vitest prints one opaque stack and every carefully worded "run the
 * generator" hint below never reaches the person who needs it. Memoised so the work still
 * happens once.
 */
let sourcesMemo: ReturnType<typeof readSealSources> | null = null
const src = () => (sourcesMemo ??= readSealSources())
let specMemo: ReturnType<typeof collectSealSpec> | null = null
const spec = () => (specMemo ??= collectSealSpec(src()))
const asset = (variant: string) => {
  const rel = SEAL_FILES[variant]
  if (!existsSync(join(ROOT, rel))) throw new Error(`${rel} is missing — ${REGENERATE}`)
  return readFileSync(join(ROOT, rel), 'utf8')
}

/** Every `<path …/>` in a generated file, in paint order. */
const paths = (svg: string) => svg.match(/<path [^>]*\/>/g) ?? []
const attr = (tag: string, name: string) => tag.match(new RegExp(`${name}="([^"]*)"`))?.[1]

describe('seal assets are generated from the component', () => {
  it('the generator reads the live path constants, not a copy of them', () => {
    // If this fails the parser has drifted, and every other assertion below is comparing
    // one wrong answer with the same wrong answer.
    expect(spec().outline).toBe(SEAL_OUTLINE)
    expect(spec().check).toBe(SEAL_CHECK)
    expect(spec().chief).toBe(SEAL_CHIEF)
    expect(spec().strokeWidth).toBe(STROKE_UI)
  })

  it.each(variants)('public seal file (%s) is byte-identical to a fresh generation', (variant) => {
    // ⚠️ THIS IS THE ONE THAT MATTERS, and it is also the real byte-stability proof: the
    // bytes on disk were generated whenever they were last committed, and this regenerates
    // them now. Anything time-varying, machine-varying or order-varying in the output shows
    // up here as a failing diff, which is why the generator may never grow a timestamp.
    expect(asset(variant), `${SEAL_FILES[variant]} is stale — ${REGENERATE}`).toBe(renderAllSeals(src())[variant])
  })

  it('the CLI agrees the checked-in files are current', () => {
    // Exercises main() and its write-only-on-difference comparison, which the pure-function
    // assertions never touch. --check writes nothing, so this test cannot repair the very
    // drift it is meant to report.
    // ⚠️ ONE INVOCATION, NOT TWO. `expect(run).not.toThrow()` followed by `run()` runs the
    // generator twice and asserts against the SECOND result — so the thing that passed and
    // the thing that was inspected are different runs.
    let out = ''
    expect(
      () => { out = execFileSync(process.execPath, [join(ROOT, 'scripts/gen-seal-svg.mjs'), '--check'], { encoding: 'utf8', cwd: ROOT }) },
      `the generator reports stale seal assets — ${REGENERATE}`,
    ).not.toThrow()
    for (const rel of Object.values(SEAL_FILES)) expect(out).toContain(`unchanged  ${rel}`)
  })

  it.each(variants)('%s carries the component paths verbatim', (variant) => {
    const svg = asset(variant)
    expect(svg, `${SEAL_FILES[variant]} does not draw SEAL_OUTLINE — ${REGENERATE}`).toContain(`d="${SEAL_OUTLINE}"`)
    expect(svg, `${SEAL_FILES[variant]} does not draw SEAL_CHECK — ${REGENERATE}`).toContain(`d="${SEAL_CHECK}"`)
  })
})

describe('the three variants match what the component renders', () => {
  it('only the wash file paints the chief, and it paints it in the WASH token colour', () => {
    // The component gates the chief behind `variant === 'wash'`; line and white omit it.
    const hex = readRootToken(src().css, washVariable(WASH))
    expect(asset('wash')).toContain(`d="${SEAL_CHIEF}" fill="${hex}"`)
    expect(asset('line')).not.toContain(SEAL_CHIEF)
    expect(asset('white')).not.toContain(SEAL_CHIEF)
  })

  it.each(variants)('%s bakes its ink instead of inheriting currentColor', (variant) => {
    // ⚠️ THE REGRESSION THIS GUARDS IS INVISIBILITY, NOT A WRONG SHADE. `currentColor` plus a
    // `color` attribute renders correctly in every browser and in librsvg — and resolves to
    // BLACK in Figma, Illustrator and slide-deck import, which is where these files are
    // actually used. seal-white.svg would then be a black mark on a dark ground.
    const svg = asset(variant)
    expect(svg).not.toContain('currentColor')
    const ink = variant === 'white' ? '#ffffff' : spec().inkHex
    for (const tag of paths(svg).filter((t) => t.includes('stroke='))) expect(attr(tag, 'stroke')).toBe(ink)
  })

  it.each(variants)('%s strokes at the STROKE_UI tier over no fill, like <EnoSeal>', (variant) => {
    const stroked = paths(asset(variant)).filter((t) => t.includes('stroke='))
    expect(stroked).toHaveLength(2)
    for (const tag of stroked) {
      expect(attr(tag, 'stroke-width')).toBe(String(STROKE_UI))
      expect(attr(tag, 'fill')).toBe('none')
    }
  })

  it.each(variants)('%s rounds the JOIN as well as the cap — the check has a vertex', (variant) => {
    // ⚠️ THIS IS THE MITER SPIKE. A hand-rolled seal once set strokeLinecap and not
    // strokeLinejoin; the old bar had no interior vertex so nothing showed, and the check
    // shipped with a sharp miter where §3 requires a round join. These files must never
    // repeat it, in any variant.
    for (const tag of paths(asset(variant)).filter((t) => t.includes('stroke='))) {
      expect(attr(tag, 'stroke-linecap')).toBe('round')
      expect(attr(tag, 'stroke-linejoin')).toBe('round')
    }
  })
})

/**
 * ⚠️ THESE MUTATIONS USE `replaceAll`, AND THE FIRST DRAFT USED `replace` AND PASSED
 * VACUOUSLY. eno-seal.tsx's header QUOTES its own code — the comment about the miter spike
 * contains the literal `strokeLinejoin="round"` — so a single `replace` deleted a sentence
 * of prose, left the JSX untouched, and "proved" a guard that had never run.
 */
describe('the generator refuses to emit a wrong seal', () => {
  it('throws when the component drops strokeLinejoin', () => {
    expect(() => readStrokeTreatment(src().component.replaceAll('strokeLinejoin="round"', ''))).toThrow(/strokeLinejoin/)
  })

  it('throws when a path constant goes missing rather than writing an empty d=""', () => {
    expect(() => collectSealSpec({ ...src(), component: src().component.replaceAll('export const SEAL_CHECK', 'const SEAL_CHECK') }))
      .toThrow(/SEAL_CHECK/)
  })

  it('refuses a path that could break out of its own attribute', () => {
    // Path data is interpolated, not escaped — so it is checked. A `"` ends the attribute and
    // everything after it becomes markup, in a file we serve from our own origin.
    expect(() => assertPathData('SEAL_CHECK', 'M8.5 11.6" onload="alert(1)')).toThrow(/path data/)
    expect(() => assertPathData('SEAL_CHECK', 'M8.5 11.6<')).toThrow(/path data/)
    // …and the gross corruptions: no moveto, or no coordinates left at all.
    expect(() => assertPathData('SEAL_CHECK', '2.6 2.6 4.6-5.2')).toThrow(/drawable/)
    expect(() => assertPathData('SEAL_CHECK', 'M')).toThrow(/drawable/)
    // …and every real path still passes, including the arcs and the Z the outline uses.
    for (const d of [SEAL_OUTLINE, SEAL_CHIEF, SEAL_CHECK]) expect(assertPathData('x', d)).toBe(d)
  })

  it('throws when the chief stops using the WASH token', () => {
    // ⚠️ THE MUTATION IS BUILT FROM `WASH`, NOT FROM THE CLASS IT HAPPENS TO HOLD TODAY.
    // Written as a literal `fill-brand-100`, a legitimate change to the token would make
    // replaceAll a no-op, the spec would build fine, and this test would fail pointing at the
    // wrong file. The replacement is a class that cannot ever BE the token, rather than
    // another real one — tsc rejects comparing `WASH` against a second literal, and picking a
    // real neighbour would only reintroduce the coupling this line exists to avoid.
    //
    // ⚠️ BOTH SPELLINGS ARE MUTATED, AND THE FIRST VERSION OF THIS TEST ONLY HANDLED ONE.
    // The generator deliberately accepts `className={WASH}` as well as the literal, calling it
    // the better form — so a test that mutates only the literal goes vacuous the day someone
    // takes that advice, and then fails with "expected function to throw" while pointing at
    // the wrong file. Two independent reviewers caught this; a guard that punishes the
    // refactor it advertises is worse than no guard.
    const wrong = 'fill-not-the-wash-token'
    const drifted = src().component
      .replaceAll(`className="${WASH}"`, `className="${wrong}"`)
      .replaceAll('className={WASH}', `className="${wrong}"`)
    expect(drifted, 'neither spelling of the chief class was found — the mutation did nothing').not.toBe(src().component)
    expect(() => collectSealSpec({ ...src(), component: drifted })).toThrow(/WASH/)
  })
})

describe('the interior is a check and the bar stays deleted', () => {
  it('the component declares no SEAL_BAR', () => {
    // Deleted 2026-08-11 (§0b). Re-adding it as a "convenience alias" is how five comments
    // came to describe a minus sign the code had not drawn for four days.
    // ⚠️ COMMENTS ARE STRIPPED FIRST, ON PURPOSE. The component's header explains at length
    // why SEAL_BAR is gone, and that paragraph must stay readable — banning the WORD would
    // delete the history that stops the next person re-adding it. The ban is on the code.
    expect(stripComments(src().component)).not.toMatch(/SEAL_BAR/)
  })

  it('the interior path of every file is the check, with its vertex intact', () => {
    // A bar is one straight segment; the check turns. Assert the drawn interior is the
    // check constant and that the constant still has more than one segment command.
    expect(SEAL_CHECK.match(/[a-zA-Z]/g)?.length).toBeGreaterThan(1)
    for (const variant of variants) {
      const interior = paths(asset(variant)).at(-1) as string
      expect(attr(interior, 'd')).toBe(SEAL_CHECK)
    }
  })
})

describe('the files are safe to hand to anything that renders SVG', () => {
  it.each(variants)('%s is self-contained and labelled', (variant) => {
    const svg = asset(variant)
    expect(svg.startsWith('<svg xmlns="http://www.w3.org/2000/svg"')).toBe(true)
    expect(svg.endsWith('</svg>\n')).toBe(true)
    expect(svg).toContain('viewBox="0 0 24 24"')
    // ⚠️ THE LABEL IS THE BRAND NAME, NOT "VERIFIED", AND THAT IS THE DECISION — asserted so
    // it is a deliberate change rather than an erosion. The app is bilingual and a static
    // file cannot call tr(), so an English meaning-word would be wrong on every VI page; an
    // <img> takes its accessible name from the embedder's alt, which CAN be translated.
    expect(svg).toContain('role="img" aria-label="eno"')
    // No remote fetches, no script, no embedded raster, no event handlers. These are served
    // from our own origin at /seal.svg, so a `<script>` or an `onload=` in one is a
    // stored-XSS shape rather than a styling bug — and a remote reference would simply not
    // render wherever the file travels.
    // ⚠️ `\s*=` — a reviewer pointed out that `onload = "…"` is valid XML and slips past a
    // pattern that demands the equals sign touch the attribute name.
    expect(svg).not.toMatch(/<(script|image|use|foreignObject)\b|url\(|\son[a-z]+\s*=/i)
    expect(svg.match(/https?:\/\/[^"' ]+/g) ?? []).toEqual(['http://www.w3.org/2000/svg'])
  })

  it.each(variants)('%s states that the mark is reserved for first-party trust', (variant) => {
    // Whoever drops an asset into a partner slot will read the file, never the script.
    expect(asset(variant)).toContain('RESERVED MARK')
    expect(asset(variant)).toContain('GENERATED FILE')
  })

  it.each(variants)('%s has no double hyphen inside its XML comment', (variant) => {
    // `--` closes an XML comment: one CSS variable name in the banner would produce a file
    // no parser will open, and the banner is the first thing anyone would want to edit.
    const comment = asset(variant).match(/<!--([\s\S]*?)-->/)?.[1] ?? ''
    expect(comment.length).toBeGreaterThan(0)
    expect(comment).not.toContain('--')
  })
})
