import { categoryTileArtPath } from '@/lib/category-art'
import { CATEGORY_ART } from '@/generated/icon-paths'
import { cn } from '@/lib/utils'
import { CategoryIcon } from './category-icons'
import { ArtImage } from '@/components/marketplace/art-image'

/**
 * A CATEGORY TILE'S GLYPH — the owner's 3D icon pack, in its own colours at every state.
 *
 * The artwork is generated by `scripts/gen-category-art.mjs` into
 * `public/icons/categories/<slug>.{avif,webp}` — 21 slugs, one per top-level category, emitted twice
 * because the browserslist floor predates AVIF (the generator explains the pair at length).
 * ⚠️ THE 2026-08-28 CONTRACT — "make it gray when not pressed and these blue versions when pressed" —
 * IS GONE, superseded twice by the owner on 2026-09-18: first the `grayscale()` came off, then the
 * single-hue pack was replaced with full-colour renders. Neither state nor colour rides a filter now.
 *
 * ⛔ THIS GIVES UP `currentColor`, AND THAT IS THE WHOLE TRADE — the note that stood here before
 * argued the opposite case and it was right for the artwork it described. Solar's outline/bold
 * pair was inlined precisely so the glyph inherited the tile's TEXT colour, which carried hover,
 * selected, dark mode and the accent flip in one mechanism. These are full-colour 3D renders:
 * there is no single colour to inherit, so none of those can ride the glyph at all.
 * What that costs, stated plainly rather than discovered later:
 *   · the glyph no longer follows the accent on hover — only scale and the label colour do;
 *   · SELECTION HAS NO CARRIER IN THE IMAGE, so the rail supplies its own: a tinted disc behind the
 *     pressed glyph plus an accent semibold label. Change either and press-state stops being visible;
 *   · dark mode gets the same pixels as light, so the artwork has to read on both grounds;
 *   · every tile is now a request instead of inline path data (they are small, cacheable and
 *     served from the same origin, but it is 21 requests that used to be zero).
 * ⚠️ If a future pack ships as flat single-colour SVG, the old approach is the better one — the
 * git history has it, and `CATEGORY_ART` in src/generated/icon-paths.ts still holds the paths.
 *
 * ⚠️ THE FILE SET AND `CATEGORY_ART` MUST STAY IN STEP. `CategoryTileGlyph` below only calls this
 * for slugs present in that registry, so an entry added there WITHOUT re-running the generator
 * renders a broken image. The generator asserts the two match; keep it that way.
 */
/**
 * ⛔ THE COLOUR IS IN THE ARTWORK NOW, NOT IN A FILTER (owner, 2026-09-18, supplying 27 new renders:
 * "compare choose and replace with relevant category glyph no more colors remade all in their own
 * original color"). THIS REPLACED A `TILE_HUE` MAP of twenty-one per-slug `hue-rotate` angles, and
 * the history is worth one paragraph because the map looked like a reasonable idea and was not:
 *
 * The old pack was twenty-one renders of the SAME blue, so removing the `grayscale()` earlier that
 * day produced a blue wall rather than the colourful one the 58 app has. `hue-rotate` was the cheap
 * way to fake variety — it leaves greys and whites alone, so highlights survived and only the body
 * of each object turned. What it CANNOT do is give an object its real colour: a rotated blue teddy
 * bear is a teddy-bear-shaped patch of whatever hue the matrix landed on, never brown. Every angle
 * had to be solved from a measured base and re-checked by eye, a pink tile was one wrong constant
 * away, and the whole apparatus existed to approximate what redrawn artwork gives for free.
 *
 * ⚠️ SO A NEW GLYPH NEEDS NO CODE HERE AT ALL — it needs a render in its own colours, dropped into
 * the pack and passed through `scripts/gen-category-art.mjs`. Do not reintroduce a per-slug filter
 * map to "brighten" or "vary" a tile; fix the source image.
 * ⚠️ ALL TWENTY-ONE ARE REDRAWN. `food-drink` and `free` arrived an hour after the other nineteen and
 * this note said they were "still the old blue" in between — three reviewers read that sentence and
 * all three reported the two tiles as a regression this diff introduced, because deleting `TILE_HUE`
 * would indeed have dropped them back to raw blue had the renders not landed. They did. Keep this
 * line honest if a future pack is ever part-delivered: a stale "unfinished" note is indistinguishable
 * from a real one.
 * ⛔ THE REVIEWERS' UNDERLYING POINT STANDS THOUGH, and it is the rule for next time: `TILE_HUE` and
 * the artwork are a PAIR. Removing the map before every slug has a colour render regresses exactly
 * the tiles the map was covering.
 */
export function CategoryArt({
  slug,
  /**
   * ⚠️ KEPT IN THE API, DELIBERATELY UNUSED HERE. The artwork no longer changes with selection —
   * it is always in colour (see the ⛔ note below) — but every call site passes this and the sibling
   * `CategoryTileGlyph` still needs it for the lucide fallback, whose glyph DOES flip fill. Dropping
   * it from this signature alone would make the two halves of one component take different props.
   */
  selected: _selected = false,
  className,
}: {
  slug: string
  selected?: boolean
  className?: string
}) {
  const src = categoryTileArtPath(slug)
  // ⚠️ A slug with no artwork returns null rather than a broken image; CategoryTileGlyph below
  // already gates on the same registry, so this is the belt to that braces.
  if (!src) return null
  return (
    <ArtImage
      src={src}
      alt=""
      aria-hidden
      width={184}
      height={184}
      draggable={false}
      /* ⚠️ `fetchPriority="low"` AND `decoding="async"`, because this went from zero requests to
         NINETEEN. They are small and same-origin, but eager full-priority fetches on the home page
         compete with the LCP image — and this repo has already paid for that once, which is why
         ui/avatar is hand-rolled. Low priority lets the hero win the network; async decode keeps
         the rail off the main thread. Deliberately NOT `loading="lazy"`: the rail is above the
         fold, and lazy would blank the tiles the visitor is looking at. */
      fetchPriority="low"
      decoding="async"
      /* ⛔ THE ARTWORK IS ALWAYS IN COLOUR SINCE 2026-09-18, and this is the single change that
         makes the home page look like the app the owner keeps pointing at: 58's grid is a wall of
         saturated marks, ours drew the same full-colour renders through `grayscale()` and only
         let the pressed one bloom. Measured on the rail: nineteen colour tiles where there was one.
         ⚠️ SELECTION THEREFORE NEEDS ANOTHER CARRIER, because colour was it. The label already goes
         accent-coloured and semibold on press, and the rail adds a tinted disc behind the pressed
         glyph — see `selected` in category-rail.tsx. Do not put the filter back without giving
         those two something to replace it with.
         ⚠️ `transition-[filter]` STAYS: dark mode still dims the art a touch (below), and the
         press feel comes from the tile's own `group-hover:scale-110`. */
      /* ⚠️ `h-11 w-11` IS A DEFAULT, NOT A FIXED SIZE — `className` comes last so a call site's
         own size wins through tailwind-merge. The old inline `<svg>` had no intrinsic size and
         filled whatever box it was given; an `<img>` with width/height 184 would paint at 184px
         for any caller that passed none, so the default matches what the rail actually asks for. */
      className={cn(
        'h-11 w-11 shrink-0 select-none object-contain transition-[filter] duration-200',
        /**
         * ⚠️ A TOUCH OF DIM ON DARK, NOT GREY: these renders are lit for a white ground and glare a
         * little on #1b1b1b at full intensity. It is the ONLY filter left on a tile now that the art
         * carries its own colour — which is also why it can be a plain utility again rather than the
         * composed `[filter:…]` pair it had to be while a hue variable shared the property.
         */
        'dark:brightness-[0.92]',
        className,
      )}
    />
  )
}

/**
 * The tile glyph a call site should reach for: Solar when the slug has artwork, the lucide
 * registry otherwise.
 *
 * ⚠️ THE FALLBACK IS THE POINT, NOT A LOOSE END. `CATEGORY_ART` covers SEVENTEEN slugs — the 15
 * taxonomy categories plus `free` and `all`. `category-icons.tsx` registers 98 immutable keys
 * (`Category.icon`, mirrored in the database) covering every category AND subcategory, so the
 * ~81 subcategory glyphs have no Solar equivalent and must keep resolving to lucide. A caller
 * addressing a subcategory passes a slug this map does not hold and gets its lucide glyph, which
 * is why this component takes BOTH a slug and a registry key.
 */
export function CategoryTileGlyph({
  slug,
  icon,
  selected = false,
  className,
}: {
  slug: string
  icon: string
  selected?: boolean
  className?: string
}) {
  return CATEGORY_ART[slug] ? (
    <CategoryArt slug={slug} selected={selected} className={className} />
  ) : (
    <CategoryIcon name={icon} selected={selected} className={className} />
  )
}
