import { categoryTileArtPath } from '@/lib/category-art'
import { CATEGORY_ART } from '@/generated/icon-paths'
import { cn } from '@/lib/utils'
import { CategoryIcon } from './category-icons'
import { ArtImage } from '@/components/marketplace/art-image'

/**
 * A CATEGORY TILE'S GLYPH — the owner's 3D icon pack, grey until the tile is chosen.
 *
 * Owner, 2026-08-28, supplying the pack: "make it gray when not pressed and these blue versions
 * when pressed". The artwork is generated by `scripts/gen-category-art.mjs` into
 * `public/icons/categories/<slug>.webp` — 19 files, one per top-level category, ~89 KB in total.
 *
 * ⛔ THIS GIVES UP `currentColor`, AND THAT IS THE WHOLE TRADE — the note that stood here before
 * argued the opposite case and it was right for the artwork it described. Solar's outline/bold
 * pair was inlined precisely so the glyph inherited the tile's TEXT colour, which carried hover,
 * selected, dark mode and the accent flip in one mechanism. These are full-colour 3D renders:
 * there is no single colour to inherit, so the state rides a `grayscale()` filter instead.
 * What that costs, stated plainly rather than discovered later:
 *   · the glyph no longer follows the accent on hover — only scale and the label colour do;
 *   · dark mode gets the same pixels as light, so the artwork has to read on both grounds;
 *   · every tile is now a request instead of inline path data (they are small, cacheable and
 *     served from the same origin, but it is 19 requests that used to be zero).
 * ⚠️ If a future pack ships as flat single-colour SVG, the old approach is the better one — the
 * git history has it, and `CATEGORY_ART` in src/generated/icon-paths.ts still holds the paths.
 *
 * ⚠️ THE FILE SET AND `CATEGORY_ART` MUST STAY IN STEP. `CategoryTileGlyph` below only calls this
 * for slugs present in that registry, so an entry added there WITHOUT re-running the generator
 * renders a broken image. The generator asserts the two match; keep it that way.
 */
export function CategoryArt({
  slug,
  selected = false,
  className,
}: {
  slug: string
  selected?: boolean
  className?: string
}) {
  const src = categoryTileArtPath(slug)
  // ⚠️ A slug with no artwork returns null rather than a broken image; CategoryTileGlyph below
  // already gates on the same registry, so this is the belt to that braces.
  if (!src) return null
  return (
    <ArtImage
      src={src}
      alt=""
      aria-hidden
      width={184}
      height={184}
      draggable={false}
      /* ⚠️ `fetchPriority="low"` AND `decoding="async"`, because this went from zero requests to
         NINETEEN. They are small and same-origin, but eager full-priority fetches on the home page
         compete with the LCP image — and this repo has already paid for that once, which is why
         ui/avatar is hand-rolled. Low priority lets the hero win the network; async decode keeps
         the rail off the main thread. Deliberately NOT `loading="lazy"`: the rail is above the
         fold, and lazy would blank the tiles the visitor is looking at. */
      fetchPriority="low"
      decoding="async"
      /* ⚠️ `grayscale` IS THE UNPRESSED STATE, not a de-emphasis effect layered on top of one —
         pressed is simply the artwork as drawn. The transition is on `filter` so the colour
         arrives with the press rather than snapping, and it is the only property animated here:
         the tile's own `group-hover:scale-110` still comes from `className`. */
      /* ⚠️ `h-11 w-11` IS A DEFAULT, NOT A FIXED SIZE — `className` comes last so a call site's
         own size wins through tailwind-merge. The old inline `<svg>` had no intrinsic size and
         filled whatever box it was given; an `<img>` with width/height 184 would paint at 184px
         for any caller that passed none, so the default matches what the rail actually asks for. */
      className={cn(
        'h-11 w-11 shrink-0 select-none object-contain transition-[filter] duration-200',
        !selected && 'grayscale',
        className,
      )}
    />
  )
}

/**
 * The tile glyph a call site should reach for: Solar when the slug has artwork, the lucide
 * registry otherwise.
 *
 * ⚠️ THE FALLBACK IS THE POINT, NOT A LOOSE END. `CATEGORY_ART` covers SEVENTEEN slugs — the 15
 * taxonomy categories plus `free` and `all`. `category-icons.tsx` registers 98 immutable keys
 * (`Category.icon`, mirrored in the database) covering every category AND subcategory, so the
 * ~81 subcategory glyphs have no Solar equivalent and must keep resolving to lucide. A caller
 * addressing a subcategory passes a slug this map does not hold and gets its lucide glyph, which
 * is why this component takes BOTH a slug and a registry key.
 */
export function CategoryTileGlyph({
  slug,
  icon,
  selected = false,
  className,
}: {
  slug: string
  icon: string
  selected?: boolean
  className?: string
}) {
  return CATEGORY_ART[slug] ? (
    <CategoryArt slug={slug} selected={selected} className={className} />
  ) : (
    <CategoryIcon name={icon} selected={selected} className={className} />
  )
}
