export const DEFAULT_EVISA_ENTRY_GATE = 'Tan Son Nhat Airport Border Gate'

export const EVISA_CHECKPOINT_GROUPS = [
  {
    id: 'air',
    label: 'Air border gates',
    labelVi: 'Cửa khẩu hàng không',
    options: [
      'Cat Bi Airport Border Gate',
      'Cam Ranh Airport Border Gate',
      'Can Tho Airport Border Gate',
      'Da Nang Airport Border Gate',
      'Noi Bai Airport Border Gate',
      'Phu Quoc Airport Border Gate',
      'Phu Bai Airport Border Gate',
      DEFAULT_EVISA_ENTRY_GATE,
      'Van Don Airport Border Gate',
      'Tho Xuan Airport Border Gate',
      'Dong Hoi Airport Border Gate',
      'Phu Cat Airport Border Gate',
      'Lien Khuong Airport Border Gate',
      'Vinh Airport Border Gate',
      'Chu Lai Airport Border Gate',
    ],
  },
  {
    id: 'land',
    label: 'Land border gates',
    labelVi: 'Cửa khẩu đường bộ',
    options: [
      'Bo Y International Border Gate, Kon Tum Province',
      'Cha Lo International Border Gate, Quang Binh Province',
      'Cau Treo International Border Gate, Ha Tinh Province',
      'Huu Nghi International Border Gate, Lang Son Province',
      'Ha Tien International Border Gate, Kien Giang Province',
      'Lao Bao International Border Gate, Quang Tri Province',
      'Lao Cai International Border Gate, Lao Cai Province',
      'La Lay International Border Gate, Quang Tri Province',
      'Moc Bai International Border Gate, Tay Ninh Province',
      'Mong Cai International Border Gate, Quang Ninh Province',
      'Nam Can International Border Gate, Nghe An Province',
      'Na Meo International Border Gate, Thanh Hoa Province',
      'Vinh Xuong International Land and River Border Gate, An Giang Province',
      'Tinh Bien International Border Gate, An Giang Province',
      'Tay Trang International Border Gate, Dien Bien Province',
      'Xa Mat International Border Gate, Tay Ninh Province',
      'Dong Dang International Border Gate, Lang Son Province',
      'Tra Linh International Border Gate, Cao Bang Province',
      'Thanh Thuy International Border Gate, Tuyen Quang Province',
      'Lao Cai International Border Gate (Railway), Lao Cai Province',
      'Long Sap International Border Gate, Son La Province',
      'Nam Giang International Border Gate, Da Nang Province',
      'Le Thanh International Border Gate, Gia Lai Province',
      'Tan Nam International Border Gate, Tay Ninh Province',
      'Binh Hiep International Border Gate, Tay Ninh Province',
      'Thuong Phuoc International Border Gate, Dong Thap Province',
      'Dinh Ba International Border Gate, Dong Thap Province',
    ],
  },
  {
    id: 'sea',
    label: 'Sea border gates',
    labelVi: 'Cửa khẩu đường biển',
    options: [
      'Chan May Port Border Gate, Thua Thien Hue Province',
      'Cam Pha Port Border Gate, Quang Ninh Province',
      'Da Nang Port Border Gate, Da Nang City',
      'Duong Dong Port Border Gate, Kien Giang Province',
      'Dung Quat Port Border Gate, Quang Ngai Province',
      'Hon Gai Port Border Gate, Quang Ninh Province',
      'Hai Phong Port Border Gate, Hai Phong City',
      'Nghi Son Port Border Gate, Thanh Hoa Province',
      'Nha Trang Port Border Gate, Khanh Hoa Province',
      'Quy Nhon Port Border Gate, Binh Dinh Province',
      'Ho Chi Minh City Port Border Gate, Ho Chi Minh City',
      'Vung Ang Port Border Gate, Ha Tinh Province',
      'Vung Tau Port Border Gate, Ba Ria - Vung Tau Province',
      'Van Gia Port Border Gate, Quang Ninh Province',
      'Ninh Phuc Port Border Gate, Ninh Binh Province',
      'Diem Dien Port Border Gate, Hung Yen Province',
      'Hai Thinh Port Border Gate, Ninh Binh Province',
      'Ben Thuy Port Border Gate, Nghe An Province',
      'Son Duong Port Border Gate, Ha Tinh Province',
      'Gianh Port Border Gate, Quang Tri Province',
      'Hon La Port Border Gate, Quang Tri Province',
      'Cua Viet Port Border Gate, Quang Tri Province',
      'Thuan An Port Border Gate, Hue City',
      'Ky Ha Port Border Gate, Da Nang Province',
      'Sa Ky Port Border Gate, Quang Ngai Province',
      'Ca Na Port Border Gate, Khanh Hoa Province',
      'Ninh Chu Port Border Gate, Khanh Hoa Province',
      'Phu Quy Port Border Gate, Lam Dong Province',
      'Dong Thap Port Border Gate, Dong Thap Province',
      'My Thoi Port Border Gate, An Giang Province',
      'Hon Chong Port Border Gate, An Giang Province',
      'An Thoi Port Border Gate, An Giang Province',
      'Ben Luc Port Border Gate, Tay Ninh Province',
      'Soai Riep - Hiep Phuoc Port Border Gate, Dong Thap Province',
      'Truong Long Hoa Port Border Gate, Vinh Long Province',
      'Nam Can Port Border Gate, Ca Mau Province',
      'Lien Huong Port Border Gate, Lam Dong Province',
      'Giao Long Port Border Gate, Vinh Long Province',
      'Vung Ro Port Border Gate, Dak Lak Province',
    ],
  },
] as const

export const EVISA_CHECKPOINTS = EVISA_CHECKPOINT_GROUPS.flatMap((group) => group.options)
