import { PrismaClient } from '@prisma/client'
import path from 'path'

// Use the same db file the app uses
const db = new PrismaClient({ log: ['warn', 'error'] })

const day = 24 * 60 * 60 * 1000
const now = Date.now()
const ago = (d: number) => new Date(now - d * day)
const future = (d: number) => new Date(now + d * day)

const img = (...paths: string[]) => JSON.stringify(paths)

async function main() {
  console.log('Seeding ENO database...')

  // Clean wipe so re-seeding updates all fields (incl. category colors)
  await db.listing.deleteMany({})
  await db.seller.deleteMany({})
  await db.category.deleteMany({})

  // ---------- Categories ----------
  const categories = await db.$transaction([
    db.category.upsert({
      where: { slug: 'moving-sale' },
      update: {},
      create: {
        name: 'Moving Sale',
        nameVi: 'Đồ Thanh Lý',
        slug: 'moving-sale',
        icon: 'PackageOpen',
        color: 'brand',
        description: 'Furniture, appliances & household items from expats moving out',
      },
    }),
    db.category.upsert({
      where: { slug: 'motorbike-rentals' },
      update: {},
      create: {
        name: 'Motorbike Rentals',
        nameVi: 'Thuê Xe Máy',
        slug: 'motorbike-rentals',
        icon: 'Bike',
        color: 'sky',
        description: 'Scooters & motorbikes for rent by the month or day',
      },
    }),
    db.category.upsert({
      where: { slug: 'house-rentals' },
      update: {},
      create: {
        name: 'House Rentals',
        nameVi: 'Cho Thuê Nhà',
        slug: 'house-rentals',
        icon: 'Home',
        color: 'teal',
        description: 'Apartments, houses & rooms verified before listing',
      },
    }),
    db.category.upsert({
      where: { slug: 'electronics' },
      update: {},
      create: {
        name: 'Electronics',
        nameVi: 'Điện Tử',
        slug: 'electronics',
        icon: 'Smartphone',
        color: 'indigo',
        description: 'Phones, laptops & gadgets — checked for real specs',
      },
    }),
    db.category.upsert({
      where: { slug: 'jobs' },
      update: {},
      create: {
        name: 'Jobs',
        nameVi: 'Việc Làm',
        slug: 'jobs',
        icon: 'Briefcase',
        color: 'violet',
        description: 'Real job openings from verified employers',
      },
    }),
    db.category.upsert({
      where: { slug: 'services' },
      update: {},
      create: {
        name: 'Services',
        nameVi: 'Dịch Vụ',
        slug: 'services',
        icon: 'Wrench',
        color: 'cyan',
        description: 'Moving, cleaning, repair & visa services you can trust',
      },
    }),
  ])

  const [
    movingCat, motoCat, houseCat, elecCat, jobsCat, servicesCat,
  ] = categories

  // ---------- Sellers ----------
  const sellers = await db.$transaction([
    db.seller.upsert({
      where: { id: 'seller-minh' },
      update: {},
      create: {
        id: 'seller-minh',
        name: 'Minh Nguyễn',
        avatarColor: '#375efb',
        rating: 4.9,
        reviewCount: 47,
        verified: true,
        verifiedSeller: true,
        memberSince: new Date('2021-03-12'),
        responseRate: 98,
        responseTime: 'within an hour',
        location: 'Thao Dien, District 2',
        bio: 'Local host helping expats settle in Saigon since 2021. All items personally inspected.',
      },
    }),
    db.seller.upsert({
      where: { id: 'seller-linh' },
      update: {},
      create: {
        id: 'seller-linh',
        name: 'Linh Phạm',
        avatarColor: '#26356d',
        rating: 5.0,
        reviewCount: 38,
        verified: true,
        verifiedSeller: true,
        memberSince: new Date('2020-08-01'),
        responseRate: 100,
        responseTime: 'within 2 hours',
        location: 'Phu My Hung, District 7',
        bio: 'Property manager in Phu My Hung. Every unit video-checked before posting.',
      },
    }),
    db.seller.upsert({
      where: { id: 'seller-david' },
      update: {},
      create: {
        id: 'seller-david',
        name: 'David Trần',
        avatarColor: '#4285f4',
        rating: 4.8,
        reviewCount: 22,
        verified: true,
        verifiedSeller: true,
        memberSince: new Date('2022-01-20'),
        responseRate: 95,
        responseTime: 'within 3 hours',
        location: 'Binh Thanh District',
        bio: 'Việt Kiều returning to HCMC. Selling household items before relocating again.',
      },
    }),
    db.seller.upsert({
      where: { id: 'seller-huong' },
      update: {},
      create: {
        id: 'seller-huong',
        name: 'Hương Lê',
        avatarColor: '#0ea5e9',
        rating: 4.9,
        reviewCount: 15,
        verified: true,
        verifiedSeller: true,
        memberSince: new Date('2021-11-05'),
        responseRate: 97,
        responseTime: 'within 4 hours',
        location: 'Da Nang',
        bio: 'Da Nang local. Long-term rentals near the beach, all verified in person.',
      },
    }),
    db.seller.upsert({
      where: { id: 'seller-sarah' },
      update: {},
      create: {
        id: 'seller-sarah',
        name: 'Sarah Nguyen',
        avatarColor: '#6366f1',
        rating: 5.0,
        reviewCount: 31,
        verified: true,
        verifiedSeller: true,
        memberSince: new Date('2022-06-18'),
        responseRate: 100,
        responseTime: 'within an hour',
        location: 'Thao Dien, District 2',
        bio: 'Aussie expat in Saigon. I only list things I have personally used.',
      },
    }),
    db.seller.upsert({
      where: { id: 'seller-quang' },
      update: {},
      create: {
        id: 'seller-quang',
        name: 'Quang Trần',
        avatarColor: '#8b5cf6',
        rating: 4.7,
        reviewCount: 19,
        verified: true,
        verifiedSeller: true,
        memberSince: new Date('2020-05-22'),
        responseRate: 94,
        responseTime: 'within 5 hours',
        location: 'Hoan Kiem, Hanoi',
        bio: 'Hanoi-based verified seller. Electronics & gadgets, spec-checked.',
      },
    }),
    db.seller.upsert({
      where: { id: 'seller-tuan' },
      update: {},
      create: {
        id: 'seller-tuan',
        name: 'Tuấn Đoàn',
        avatarColor: '#64748b',
        rating: 4.2,
        reviewCount: 4,
        verified: false,
        verifiedSeller: false,
        memberSince: new Date('2024-09-01'),
        responseRate: 60,
        responseTime: '1–2 days',
        location: 'District 1',
        bio: 'New account. Listings pending verification.',
      },
    }),
    db.seller.upsert({
      where: { id: 'seller-mai' },
      update: {},
      create: {
        id: 'seller-mai',
        name: 'Mai Hoàng',
        avatarColor: '#06b6d4',
        rating: 4.8,
        reviewCount: 12,
        verified: true,
        verifiedSeller: true,
        memberSince: new Date('2023-02-10'),
        responseRate: 96,
        responseTime: 'within 3 hours',
        location: 'District 4',
        bio: 'Service provider — moving & cleaning crews across HCMC.',
      },
    }),
  ])

  const [sMinh, sLinh, sDavid, sHuong, sSarah, sQuang, sTuan, sMai] = sellers

  // ---------- Listings ----------
  // Helper to build a listing object
  type L = Parameters<typeof db.listing.create>[0]['data']

  const listings: L[] = [
    // ===== Moving Sale =====
    {
      title: '3-seat fabric sofa set — like new, moving overseas',
      titleVi: 'Bộ ghế sofa 3 chỗ — còn mới, chuyển đi',
      description:
        'Bought 14 months ago from IKEA Saigon for our Thao Dien apartment. Light beige fabric, no stains, no tears. Comes with 4 matching cushions. Selling because we are relocating to Singapore. Inspected in person by an ENO agent on 12 May — photos match the real item. Cash or bank transfer. Pickup from ground floor, elevator available.',
      price: 3500000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Like new',
      images: img('/listings/furniture-sofa.png'),
      categoryId: movingCat.id,
      sellerId: sMinh.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(9),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Item physically inspected. Serial/tag confirmed. Photos match.',
      postedAt: ago(10),
      views: 1240,
      savedCount: 86,
      featured: true,
      attributes: JSON.stringify({ brand: 'IKEA', age: '14 months', pickup: 'Ground floor, elevator' }),
    },
    {
      title: 'Wooden bed frame + mattress (queen)',
      titleVi: 'Giường gỗ + nệm (queen)',
      description:
        'Solid oak bed frame with slatted base + 25cm memory-foam mattress. Used 2 years, mattress always protected with cover. No bedbugs (treated + certified). Moving to a furnished place so no longer needed. Verified by video call — seller showed item live and measurement matched description.',
      price: 2800000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Phu My Hung, District 7',
      district: 'District 7',
      city: 'Ho Chi Minh City',
      condition: 'Good',
      images: img('/listings/furniture-bedroom.png'),
      categoryId: movingCat.id,
      sellerId: sLinh.id,
      verified: true,
      verificationMethod: 'video-call',
      verifiedAt: ago(6),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Live video walkthrough completed. Dimensions 160x200cm confirmed.',
      postedAt: ago(7),
      views: 642,
      savedCount: 51,
      featured: false,
      attributes: JSON.stringify({ size: 'Queen 160x200', material: 'Solid oak', age: '2 years' }),
    },
    {
      title: 'Refrigerator + microwave (moving sale bundle)',
      titleVi: 'Tủ lạnh + lò vi sóng (thanh lý)',
      description:
        'Samsung 220L double-door fridge + Toshiba microwave. Both working perfectly, cold-tested. Fridge has one small dent on the side (shown in inspection notes). Bundle only, not selling separately. In-person verified.',
      price: 4200000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: false,
      location: 'Binh Thanh District',
      district: 'Binh Thanh',
      city: 'Ho Chi Minh City',
      condition: 'Good',
      images: img('/listings/furniture-sofa.png'),
      categoryId: movingCat.id,
      sellerId: sDavid.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(4),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Both appliances powered on and tested for 30 min. Dent documented.',
      postedAt: ago(5),
      views: 388,
      savedCount: 29,
      featured: false,
      attributes: JSON.stringify({ bundle: true, fridgeL: 220, brand: 'Samsung / Toshiba' }),
    },
    {
      title: 'Dining table + 6 chairs (solid wood)',
      titleVi: 'Bàn ăn + 6 ghế (gỗ tự nhiên)',
      description:
        'Extendable dining table (120→180cm) with 6 matching chairs. Teak wood, made in Binh Duong workshop. Minor surface scratches, otherwise sturdy. Verified in person by agent.',
      price: 1900000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Phu My Hung, District 7',
      district: 'District 7',
      city: 'Ho Chi Minh City',
      condition: 'Used',
      images: img(),
      categoryId: movingCat.id,
      sellerId: sHuong.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(3),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Table extends smoothly. All 6 chairs stable.',
      postedAt: ago(4),
      views: 210,
      savedCount: 17,
      featured: false,
      attributes: JSON.stringify({ material: 'Teak', extends: '120→180cm', seats: 6 }),
    },

    // ===== Motorbike Rentals =====
    {
      title: 'Honda Air Blade 160 — monthly rental, full papers',
      titleVi: 'Honda Air Blade 160 — thuê tháng, đủ giấy tờ',
      description:
        '2023 Honda Air Blade 160cc, automatic, 8,500km. Includes 2 helmets, phone holder, raincoat. Full registration (cavet xe) verified and on file. Free delivery within District 1/2/Binh Thanh. Deposit 5,000,000₫ refunded on return. Bike + papers inspected in person by ENO agent — this is NOT a photo-only listing.',
      price: 1800000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Excellent',
      images: img('/listings/motorbike-airblade.png'),
      categoryId: motoCat.id,
      sellerId: sMinh.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(8),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Bike VIN matched registration. Engine started cold. Tyres 70%.',
      postedAt: ago(12),
      views: 2105,
      savedCount: 164,
      featured: true,
      attributes: JSON.stringify({ cc: 160, year: 2023, transmission: 'Automatic', deposit: 5000000, delivery: 'Free D1/D2/Binh Thanh' }),
    },
    {
      title: 'Honda Wave Alpha 110 — cheap monthly rental',
      titleVi: 'Honda Wave Alpha 110 — thuê tháng giá rẻ',
      description:
        'Honda Wave Alpha 110cc, manual, the classic reliable daily commuter. 18,000km, well-serviced every 2,000km (service log provided). Includes 1 helmet. Great for budget expats. Papers verified in person.',
      price: 1200000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Ben Nghe, District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'Good',
      images: img('/listings/motorbike-wave.png'),
      categoryId: motoCat.id,
      sellerId: sQuang.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(5),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Frame number matches registration. Brake pads replaced recently.',
      postedAt: ago(6),
      views: 980,
      savedCount: 72,
      featured: false,
      attributes: JSON.stringify({ cc: 110, year: 2021, transmission: 'Manual', deposit: 3000000 }),
    },
    {
      title: 'Yamaha Exciter 155 — sport bike rental',
      titleVi: 'Yamaha Exciter 155 — thuê xe thể thao',
      description:
        'Yamaha Exciter 155 VVA, manual 6-speed. For riders with experience. Includes full papers and insurance. Verified by video call + document check.',
      price: 2200000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: true,
      location: 'Binh Thanh District',
      district: 'Binh Thanh',
      city: 'Ho Chi Minh City',
      condition: 'Excellent',
      images: img(),
      categoryId: motoCat.id,
      sellerId: sDavid.id,
      verified: true,
      verificationMethod: 'video-call',
      verifiedAt: ago(2),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Video walkthrough + registration document uploaded & validated.',
      postedAt: ago(3),
      views: 540,
      savedCount: 41,
      featured: false,
      attributes: JSON.stringify({ cc: 155, year: 2022, transmission: 'Manual 6-speed', deposit: 6000000 }),
    },
    {
      title: 'Honda Vision 125 — automatic scooter rental',
      titleVi: 'Honda Vision 125 — xe tay ga thuê tháng',
      description:
        'Lightweight automatic scooter, perfect for the city. 12,000km, female-owned, very clean. Includes 2 helmets + raincoat. Document-checked and verified.',
      price: 1500000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Phu My Hung, District 7',
      district: 'District 7',
      city: 'Ho Chi Minh City',
      condition: 'Excellent',
      images: img(),
      categoryId: motoCat.id,
      sellerId: sLinh.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(7),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Registration document validated against national DB.',
      postedAt: ago(8),
      views: 720,
      savedCount: 58,
      featured: false,
      attributes: JSON.stringify({ cc: 125, year: 2022, transmission: 'Automatic', deposit: 4000000 }),
    },

    // ===== House Rentals =====
    {
      title: '1-bedroom apartment in Thao Dien — pool & gym',
      titleVi: 'Căn hộ 1 phòng ngủ Thao Dien — hồ bơi & gym',
      description:
        'Bright 1BR apartment in The Estella, Thao Dien. 48m², fully furnished, balcony with city view. Building has pool, gym, 24/7 security, and a large expat community. Walk to British International School & Vincom. Rent includes management fee. Verified in person by agent — real unit, real price, real availability (available from 1 June).',
      price: 18000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Furnished',
      images: img('/listings/apartment-thaodien.png'),
      categoryId: houseCat.id,
      sellerId: sMinh.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(5),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Unit visited. Key handed by building management. Availability confirmed.',
      postedAt: ago(6),
      views: 3120,
      savedCount: 218,
      featured: true,
      attributes: JSON.stringify({ size: '48m²', bedrooms: 1, bathrooms: 1, building: 'The Estella', available: '1 June', amenities: ['pool', 'gym', 'security'] }),
    },
    {
      title: '2-bedroom apartment in Phu My Hung — family friendly',
      titleVi: 'Căn hộ 2 phòng ngủ Phu My Hung — hợp gia đình',
      description:
        'Spacious 2BR in Sunrise City, Phu My Hung. 78m², modern kitchen, 2 bathrooms, fully furnished. Walking distance to Crescent Mall, FV Hospital, and international schools. Verified by video walkthrough + document check.',
      price: 24000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: true,
      location: 'Phu My Hung, District 7',
      district: 'District 7',
      city: 'Ho Chi Minh City',
      condition: 'Furnished',
      images: img('/listings/apartment-phumyhung.png'),
      categoryId: houseCat.id,
      sellerId: sLinh.id,
      verified: true,
      verificationMethod: 'video-call',
      verifiedAt: ago(4),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Video tour of full unit + ownership doc validated.',
      postedAt: ago(5),
      views: 1840,
      savedCount: 132,
      featured: true,
      attributes: JSON.stringify({ size: '78m²', bedrooms: 2, bathrooms: 2, building: 'Sunrise City', available: 'now', amenities: ['pool', 'gym', 'parking'] }),
    },
    {
      title: 'Studio apartment near District 1 — walking to work',
      titleVi: 'Căn hộ studio gần Quận 1 — đi bộ đi làm',
      description:
        'Compact 30m² studio in Binh Thanh, 10 min walk to District 1. Kitchenette, AC, hot water, fast WiFi. Ideal for singles or remote workers. Verified in person.',
      price: 12000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Binh Thanh District',
      district: 'Binh Thanh',
      city: 'Ho Chi Minh City',
      condition: 'Furnished',
      images: img(),
      categoryId: houseCat.id,
      sellerId: sDavid.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(3),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Unit checked. AC & water heater tested.',
      postedAt: ago(4),
      views: 990,
      savedCount: 77,
      featured: false,
      attributes: JSON.stringify({ size: '30m²', bedrooms: 0, bathrooms: 1, available: '15 May' }),
    },
    {
      title: 'Shared room in expat house — Binh Thanh',
      titleVi: 'Phòng shared trong nhà expat — Bình Thạnh',
      description:
        'Single bed in a shared 3-bedroom house with 2 other expats (working professionals). Shared kitchen, living room, rooftop terrace. All bills split equally. Friendly, quiet house. Verified in person.',
      price: 4500000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Binh Thanh District',
      district: 'Binh Thanh',
      city: 'Ho Chi Minh City',
      condition: 'Furnished',
      images: img(),
      categoryId: houseCat.id,
      sellerId: sSarah.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(2),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'House visited. Current housemates met. Room as described.',
      postedAt: ago(3),
      views: 610,
      savedCount: 44,
      featured: false,
      attributes: JSON.stringify({ type: 'Shared room', housemates: 2, deposit: '1 month' }),
    },
    {
      title: '3-bedroom house near Da Nang beach — long term',
      titleVi: 'Nhà 3 phòng ngủ gần biển Đà Nẵng — dài hạn',
      description:
        'Whole house, 3 bedrooms, 2 bathrooms, small garden, 5 min walk to My Khe beach. Quiet alley, safe neighborhood. Great for families or remote workers. Verified in person by Da Nang agent.',
      price: 28000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: true,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Partly furnished',
      images: img(),
      categoryId: houseCat.id,
      sellerId: sHuong.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(6),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'House visited. Landlord ID verified. Lease template provided.',
      postedAt: ago(7),
      views: 1130,
      savedCount: 89,
      featured: false,
      attributes: JSON.stringify({ size: '120m²', bedrooms: 3, bathrooms: 2, available: '1 July', garden: true }),
    },

    // ===== Electronics =====
    {
      title: 'MacBook Pro M2 14" — 512GB, under warranty',
      titleVi: 'MacBook Pro M2 14" — 512GB, còn bảo hành',
      description:
        'MacBook Pro 14" M2 Pro, 16GB RAM, 512GB SSD. Bought Jan 2024, Apple warranty until Jan 2026. Battery cycle count 47. No scratches, always in case. Original box + charger included. Spec-checked by agent — serial number validated on Apple coverage website.',
      price: 28500000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Vinhomes Central Park, Binh Thanh',
      district: 'Binh Thanh',
      city: 'Ho Chi Minh City',
      condition: 'Like new',
      images: img('/listings/electronics-macbook.png'),
      categoryId: elecCat.id,
      sellerId: sQuang.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(2),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Serial verified on checkcoverage.apple.com. Specs match Apple invoice.',
      postedAt: ago(3),
      views: 1640,
      savedCount: 121,
      featured: true,
      attributes: JSON.stringify({ cpu: 'M2 Pro', ram: '16GB', storage: '512GB', warranty: 'until Jan 2026', cycles: 47 }),
    },
    {
      title: 'iPhone 14 128GB — blue, battery 92%',
      titleVi: 'iPhone 14 128GB — xanh, pin 92%',
      description:
        'iPhone 14 128GB, blue. Used 1.5 years, always with screen protector + case. Battery health 92%. No repairs, all original. IMEI verified against Apple & carrier — not blacklisted, not stolen.',
      price: 14900000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Good',
      images: img('/listings/electronics-iphone.png'),
      categoryId: elecCat.id,
      sellerId: sSarah.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(1),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'IMEI checked — clean. Battery health confirmed via settings.',
      postedAt: ago(2),
      views: 870,
      savedCount: 63,
      featured: false,
      attributes: JSON.stringify({ storage: '128GB', color: 'Blue', battery: '92%', warranty: 'expired' }),
    },
    {
      title: 'Sony WH-1000XM4 headphones — noise cancelling',
      titleVi: 'Tai nghe Sony WH-1000XM4 — chống ồn',
      description:
        'Sony WH-1000XM4, black. Excellent condition, 1 year old. Original case, cable, and adapter included. Noise cancelling tested. Verified in person.',
      price: 2200000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: false,
      location: 'Phu My Hung, District 7',
      district: 'District 7',
      city: 'Ho Chi Minh City',
      condition: 'Like new',
      images: img(),
      categoryId: elecCat.id,
      sellerId: sLinh.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(4),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Item inspected, paired and audio tested.',
      postedAt: ago(5),
      views: 420,
      savedCount: 31,
      featured: false,
      attributes: JSON.stringify({ color: 'Black', age: '1 year' }),
    },
    {
      title: 'iPad Air 5 64GB — with Apple Pencil',
      titleVi: 'iPad Air 5 64GB — kèm Apple Pencil',
      description:
        'iPad Air 5th gen, 64GB, WiFi, space gray. Includes Apple Pencil 2 (genuine). Light usage, no dents. Serial validated. Great for drawing or remote work.',
      price: 16500000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Binh Thanh District',
      district: 'Binh Thanh',
      city: 'Ho Chi Minh City',
      condition: 'Good',
      images: img(),
      categoryId: elecCat.id,
      sellerId: sDavid.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(3),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Serial validated. Pencil pairs & charges.',
      postedAt: ago(4),
      views: 530,
      savedCount: 38,
      featured: false,
      attributes: JSON.stringify({ gen: '5th', storage: '64GB', color: 'Space Gray', pencil: true }),
    },

    // ===== Jobs =====
    {
      title: 'Barista — specialty coffee shop, Thao Dien',
      titleVi: 'Barista — quán cà phê specialty, Thao Diên',
      description:
        'Full-time barista position at a specialty coffee shop in Thao Dien. Experience with espresso machines required. English-speaking environment. Salary 12,000,000₫/month + tips + meals. Employer verified (business license + shop visit by agent). This is a real, active opening — not a CV-harvesting fake post.',
      price: 12000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Full-time',
      images: img('/listings/job-cafe.png'),
      categoryId: jobsCat.id,
      sellerId: sMinh.id,
      verified: true,
      verificationMethod: 'agent-visit',
      verifiedAt: ago(4),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Shop visited. Manager interviewed. Business license on file.',
      postedAt: ago(5),
      views: 740,
      savedCount: 52,
      featured: true,
      attributes: JSON.stringify({ type: 'Full-time', hours: '40h/week', english: 'Required', benefits: ['tips', 'meals'] }),
    },
    {
      title: 'English tutor — part time, HCMC & online',
      titleVi: 'Gia sư tiếng Anh — bán thời gian, TP.HCM & online',
      description:
        'Tutoring center hiring native/near-native English speakers for evening classes + online sessions. Teaching cert preferred but not required. 350,000–500,000₫/hour. Employer verified.',
      price: 25000000,
      priceUnit: 'VND/month (est.)',
      currency: '₫',
      negotiable: true,
      location: 'District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'Part-time',
      images: img(),
      categoryId: jobsCat.id,
      sellerId: sMai.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(3),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Business license + center visited.',
      postedAt: ago(4),
      views: 980,
      savedCount: 71,
      featured: false,
      attributes: JSON.stringify({ type: 'Part-time', rate: '350k–500k/hour', schedule: 'Evenings + online' }),
    },
    {
      title: 'Remote software engineer — international team',
      titleVi: 'Kỹ sư phần mềm remote — đội quốc tế',
      description:
        'Full-stack engineer (React/Node) for a remote-first product company. Work from anywhere in Vietnam. Salary 2,500–4,500 USD/month depending on level. Employer verified via registered company + signed contract template.',
      price: 45000000,
      priceUnit: 'VND/month (est.)',
      currency: '₫',
      negotiable: true,
      location: 'Remote (Vietnam)',
      district: 'Remote',
      city: 'Vietnam',
      condition: 'Full-time',
      images: img(),
      categoryId: jobsCat.id,
      sellerId: sQuang.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(2),
      verifiedBy: 'Agent #A33 — Hanoi',
      verificationNotes: 'Company registration validated. Hiring manager reference checked.',
      postedAt: ago(3),
      views: 1320,
      savedCount: 98,
      featured: false,
      attributes: JSON.stringify({ type: 'Full-time remote', stack: 'React/Node', salaryUSD: '2,500–4,500' }),
    },
    {
      title: 'Server — Vietnamese restaurant, District 1',
      titleVi: 'Phục vụ — nhà hàng Việt, Quận 1',
      description:
        'Restaurant server position, evening shifts. Basic English helpful for tourists. 9,000,000₫/month + service charge. Employer verified via shop visit.',
      price: 9000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'Full-time',
      images: img(),
      categoryId: jobsCat.id,
      sellerId: sMai.id,
      verified: true,
      verificationMethod: 'agent-visit',
      verifiedAt: ago(1),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Restaurant visited. Owner interviewed.',
      postedAt: ago(2),
      views: 410,
      savedCount: 24,
      featured: false,
      attributes: JSON.stringify({ type: 'Full-time', shifts: 'Evenings', english: 'Helpful' }),
    },

    // ===== Services =====
    {
      title: 'Moving service — truck + 2 movers, HCMC',
      titleVi: 'Dịch vụ chuyển nhà — xe + 2 nhân viên, TP.HCM',
      description:
        'Reliable moving crew with 1.5-ton truck + 2 movers. Packing materials available. Covers all HCMC districts. Fixed quote after a free on-site estimate. Service provider verified — business registered, crew ID-checked, real reviews.',
      price: 1500000,
      priceUnit: 'VND/service (from)',
      currency: '₫',
      negotiable: true,
      location: 'District 4',
      district: 'District 4',
      city: 'Ho Chi Minh City',
      condition: 'Service',
      images: img('/listings/service-moving.png'),
      categoryId: servicesCat.id,
      sellerId: sMai.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(5),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Business license + truck plate verified. Crew IDs on file.',
      postedAt: ago(6),
      views: 880,
      savedCount: 66,
      featured: true,
      attributes: JSON.stringify({ truck: '1.5 ton', crew: 2, coverage: 'All HCMC', quote: 'Free on-site' }),
    },
    {
      title: 'Home cleaning — trusted crew, per visit',
      titleVi: 'Dịch vụ dọn nhà — đội uy tín, theo lần',
      description:
        'Professional cleaning crew for apartments & houses. 2–3 people, 3–4 hours, supplies included. Background-checked cleaners. From 350,000₫/visit. Verified service.',
      price: 350000,
      priceUnit: 'VND/visit (from)',
      currency: '₫',
      negotiable: false,
      location: 'Ho Chi Minh City',
      district: 'All districts',
      city: 'Ho Chi Minh City',
      condition: 'Service',
      images: img(),
      categoryId: servicesCat.id,
      sellerId: sMai.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(3),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Cleaner IDs + police record check on file.',
      postedAt: ago(4),
      views: 560,
      savedCount: 47,
      featured: false,
      attributes: JSON.stringify({ crew: '2–3', duration: '3–4 hours', supplies: 'Included' }),
    },
    {
      title: 'Visa & translation support — expat paperwork',
      titleVi: 'Hỗ trợ visa & dịch thuật — giấy tờ expat',
      description:
        'Licensed agent helping expats with TRC, visa extensions, work permits, and certified Vietnamese–English translation. Transparent fixed pricing. Verified business.',
      price: 500000,
      priceUnit: 'VND/service (from)',
      currency: '₫',
      negotiable: true,
      location: 'District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'Service',
      images: img(),
      categoryId: servicesCat.id,
      sellerId: sSarah.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(2),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Agent license number validated with immigration office.',
      postedAt: ago(3),
      views: 390,
      savedCount: 35,
      featured: false,
      attributes: JSON.stringify({ licensed: true, services: ['TRC', 'visa', 'work permit', 'translation'] }),
    },
    {
      title: 'Motorbike repair & servicing — mobile, comes to you',
      titleVi: 'Sửa xe máy & bảo dưỡng — dịch vụ tận nơi',
      description:
        'Mobile mechanic servicing scooters & motorbikes at your home or office. Oil change, brake, tyre, general service. Honest pricing, real parts. From 200,000₫/visit. Verified mechanic.',
      price: 200000,
      priceUnit: 'VND/visit (from)',
      currency: '₫',
      negotiable: false,
      location: 'Ho Chi Minh City',
      district: 'D1/D2/D7/Binh Thanh',
      city: 'Ho Chi Minh City',
      condition: 'Service',
      images: img(),
      categoryId: servicesCat.id,
      sellerId: sDavid.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(4),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Mechanic met. Tool kit & parts source verified.',
      postedAt: ago(5),
      views: 670,
      savedCount: 58,
      featured: false,
      attributes: JSON.stringify({ mobile: true, services: ['oil change', 'brake', 'tyre', 'general'] }),
    },
    {
      title: 'Solid Oak Wardrobe — spacious cabinet with drawers',
      titleVi: 'Tủ quần áo gỗ sồi — tủ rộng kèm ngăn kéo',
      description:
        'High-quality solid oak wardrobe/cabinet purchased 18 months ago. Two sliding doors, hanging rail, and 3 built-in drawers. Moving out sale. Verified in person by an ENO inspector.',
      price: 4500000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Phu My Hung, District 7',
      district: 'District 7',
      city: 'Ho Chi Minh City',
      condition: 'Like new',
      images: img(),
      categoryId: movingCat.id,
      sellerId: sLinh.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(3),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Wardrobe checked. Sliding doors and drawers open smoothly.',
      postedAt: ago(4),
      views: 350,
      savedCount: 22,
      featured: false,
      attributes: JSON.stringify({ material: 'Solid Oak', dimensions: '120x60x200cm', drawers: 3 }),
    },
    {
      title: 'Honda SH 150i ABS — premium rental, pristine condition',
      titleVi: 'Honda SH 150i ABS — xe thuê cao cấp, như mới',
      description:
        'Premium Honda SH 150i with ABS brakes. Black color, 2022 model, only 6,200km. Well-maintained, pristine engine. Comes with 2 high-quality helmets. cavet documents verified by ENO.',
      price: 3200000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Excellent',
      images: img(),
      categoryId: motoCat.id,
      sellerId: sMinh.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(5),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Tested ABS brakes and oil level. cavet registration matches vehicle VIN.',
      postedAt: ago(6),
      views: 520,
      savedCount: 38,
      featured: false,
      attributes: JSON.stringify({ cc: 150, year: 2022, brake: 'ABS', deposit: 8000000 }),
    },
    {
      title: '3-Bedroom Townhouse in Hanoi near West Lake',
      titleVi: 'Nhà nguyên căn 3 phòng ngủ Tây Hồ Hà Nội',
      description:
        'Beautiful 3-bedroom whole house townhouse in Tay Ho, Hanoi. Spacious living area, 3 bathrooms, rooftop terrace with lake views. Fully furnished. Available for long-term contract. Verified in person.',
      price: 35000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: true,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Furnished',
      images: img(),
      categoryId: houseCat.id,
      sellerId: sQuang.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(4),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'House walkthrough completed. Landlord papers and key validated.',
      postedAt: ago(5),
      views: 450,
      savedCount: 33,
      featured: false,
      attributes: JSON.stringify({ size: '150m²', bedrooms: 3, bathrooms: 3, floorCount: 3, garden: true }),
    },
    {
      title: 'Sony A7 IV Mirrorless Camera — body only',
      titleVi: 'Máy ảnh Sony A7 IV Mirrorless — chỉ body',
      description:
        'Sony A7 IV camera body in perfect condition. Shutter count only 4,200. Comes with original battery, strap, charger, and box. Verified in person by an ENO agent.',
      price: 43000000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: true,
      location: 'Phu My Hung, District 7',
      district: 'District 7',
      city: 'Ho Chi Minh City',
      condition: 'Like new',
      images: img(),
      categoryId: elecCat.id,
      sellerId: sLinh.id,
      verified: true,
      verificationMethod: 'in-person',
      verifiedAt: ago(2),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Tested sensor, hotshoe, and battery health. Shutter count confirmed via EXIF.',
      postedAt: ago(3),
      views: 290,
      savedCount: 18,
      featured: false,
      attributes: JSON.stringify({ model: 'A7 IV', brand: 'Sony', shutterCount: 4200, sensor: 'Full-frame' }),
    },
    {
      title: 'English Sales Executive — expat relocation center',
      titleVi: 'Nhân viên kinh doanh tiếng Anh — dịch vụ expat',
      description:
        'We are hiring an English-speaking Sales and Customer Support Executive for our relocation center in HCMC. Assist foreign clients with visa, moving, and housing services. Basic Vietnamese is a plus. Salary 15,000,000₫/month + commissions.',
      price: 15000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: true,
      location: 'District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'Full-time',
      images: img(),
      categoryId: jobsCat.id,
      sellerId: sMai.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(3),
      verifiedBy: 'Agent #A07 — HCMC',
      verificationNotes: 'Business registry check passed. HR coordinator credentials confirmed.',
      postedAt: ago(4),
      views: 380,
      savedCount: 25,
      featured: false,
      attributes: JSON.stringify({ position: 'Sales Executive', language: 'English', bonus: 'Commissions' }),
    },
    {
      title: 'Vietnamese Lessons for Expats — 1-on-1 tutoring',
      titleVi: 'Dạy tiếng Việt cho người nước ngoài — gia sư 1 kèm 1',
      description:
        'Learn communicative Vietnamese from an experienced tutor in Thao Dien or online. Tailored syllabus for expats. Flexible schedules. Certified teacher. Verified credentials.',
      price: 250000,
      priceUnit: 'VND/hour',
      currency: '₫',
      negotiable: true,
      location: 'Thao Dien, District 2',
      district: 'District 2',
      city: 'Ho Chi Minh City',
      condition: 'Service',
      images: img(),
      categoryId: servicesCat.id,
      sellerId: sSarah.id,
      verified: true,
      verificationMethod: 'document-check',
      verifiedAt: ago(1),
      verifiedBy: 'Agent #A12 — HCMC',
      verificationNotes: 'Teaching degree and language certificates checked & verified.',
      postedAt: ago(2),
      views: 180,
      savedCount: 15,
      featured: false,
      attributes: JSON.stringify({ rate: '250k/hour', location: 'Home/Online', level: 'Beginner to Advanced' }),
    },

    // ===== PENDING (unverified — held for review, NOT in main feed) =====
    {
      title: 'Brand new iPhone 15 Pro Max 1TB — 90% OFF (!!!)',
      titleVi: 'iPhone 15 Pro Max 1TB mới 100% — giảm 90% (!!!)',
      description:
        'Pending review — this listing was flagged by our automated scam detector for an unrealistic price and will not be shown to buyers until an ENO agent verifies the item in person.',
      price: 3000000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: false,
      location: 'District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'New',
      images: img(),
      categoryId: elecCat.id,
      sellerId: sTuan.id,
      verified: false,
      verificationMethod: null,
      verifiedAt: null,
      verifiedBy: null,
      verificationNotes: 'FLAGGED: price 95% below market. Awaiting in-person inspection.',
      postedAt: ago(1),
      views: 0,
      savedCount: 0,
      featured: false,
      attributes: JSON.stringify({ flag: 'unrealistic-price', status: 'awaiting-inspection' }),
    },
    {
      title: 'Luxury 3BR apartment in D1 — only 2,000,000/month',
      titleVi: 'Căn hộ 3PN hạng sang Quận 1 — chỉ 2 triệu/tháng',
      description:
        'Pending review — flagged for bait pricing. Will be hidden until verified.',
      price: 2000000,
      priceUnit: 'VND/month',
      currency: '₫',
      negotiable: false,
      location: 'District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'Furnished',
      images: img(),
      categoryId: houseCat.id,
      sellerId: sTuan.id,
      verified: false,
      verificationMethod: null,
      verifiedAt: null,
      verifiedBy: null,
      verificationNotes: 'FLAGGED: price 90% below market for area & size. Awaiting agent visit.',
      postedAt: ago(1),
      views: 0,
      savedCount: 0,
      featured: false,
      attributes: JSON.stringify({ flag: 'bait-price', status: 'awaiting-inspection' }),
    },
    {
      title: 'Brand new Honda Air Blade — 500,000 VND (!!!)',
      titleVi: 'Honda Air Blade mới 100% — 500.000đ (!!!)',
      description:
        'Pending review — flagged. Hidden from buyers until verified.',
      price: 500000,
      priceUnit: 'VND',
      currency: '₫',
      negotiable: false,
      location: 'District 1',
      district: 'District 1',
      city: 'Ho Chi Minh City',
      condition: 'New',
      images: img(),
      categoryId: motoCat.id,
      sellerId: sTuan.id,
      verified: false,
      verificationMethod: null,
      verifiedAt: null,
      verifiedBy: null,
      verificationNotes: 'FLAGGED: price 99% below market. Awaiting inspection.',
      postedAt: ago(1),
      views: 0,
      savedCount: 0,
      featured: false,
      attributes: JSON.stringify({ flag: 'unrealistic-price', status: 'awaiting-inspection' }),
    },
  ]

  // Wipe & recreate listings (clean seed)
  await db.listing.deleteMany({})
  for (const l of listings) {
    await db.listing.create({ data: l })
  }

  console.log(`Seeded ${listings.length} listings, ${sellers.length} sellers, ${categories.length} categories.`)
  console.log('Done.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await db.$disconnect()
  })
