#!/usr/bin/env bash
# Regenerate /etc/nginx/snippets/eno-realip.conf from Cloudflare's published ranges.
#
# ⛔ WHY THIS EXISTS. src/lib/client-ip.ts reads `cf-connecting-ip` first and falls
# back to `x-real-ip`. Cloudflare always sets cf-connecting-ip for proxied traffic,
# so the fallback is normally unreachable — but if it IS reached, nginx would be
# handing the app a Cloudflare EDGE ip, and the comment in that file spells out the
# consequence: every visitor buckets by edge node, so a busy PoP false-trips real
# users and an attacker evades limits by hopping edges. An edge IP is worse than
# no IP, because it looks legitimate.
#
# real_ip_header rewrites $remote_addr itself, so X-Real-IP, X-Forwarded-For AND
# the access log all become the true client — the fallback stops being a trap.
#
# ⚠️ set_real_ip_from is a TRUST list. Only Cloudflare ranges belong here; adding
# anything else lets that host forge CF-Connecting-IP and defeat every IP-keyed
# limit in the app.
#
# Re-run when Cloudflare publishes new ranges (rare), then `nginx -t && systemctl reload nginx`.
set -euo pipefail
OUT=/etc/nginx/snippets/eno-realip.conf
TMP=$(mktemp)

# ⛔ `while read` SILENTLY DROPS A FINAL LINE WITH NO TRAILING NEWLINE, and
# Cloudflare's lists end without one. The first version of this script did exactly
# that and wrote 20 of 22 ranges — losing 131.0.72.0/22 and 2c0f:f248::/32, the
# last entry of each list. Nothing failed; requests from those two PoP ranges
# simply kept a Cloudflare edge address as $remote_addr, which is the one outcome
# this file exists to prevent. `|| [ -n "$line" ]` runs the body for that last
# line too. Caught by a reviewer, not by the guard below — see why underneath.
# ⚠️ 20s WAS TOO TIGHT FROM THIS BOX — the first run of the fixed script died on
# `curl: (28) Connection timed out`. It failed safely (set -e, and the old file was
# left in place rather than replaced by a partial one), but a generator that cannot
# reach its source is a generator nobody re-runs. Retry, and be patient.
fetch() {
  for attempt in 1 2 3; do
    if curl -fsS --max-time 60 --retry 2 --retry-delay 3 "$1"; then return 0; fi
    sleep 3
  done
  echo "REFUSING: could not fetch $1 after 3 attempts" >&2
  return 1
}
V4=$(fetch https://www.cloudflare.com/ips-v4)
V6=$(fetch https://www.cloudflare.com/ips-v6)
EXPECTED=$(printf '%s\n%s\n' "$V4" "$V6" | grep -c '/')

{
  echo "# GENERATED by gen-cloudflare-realip.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not edit by hand."
  printf '%s\n%s\n' "$V4" "$V6" | while read -r line || [ -n "$line" ]; do
    case "$line" in */*) echo "set_real_ip_from $line;" ;; esac
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

# ⛔ COMPARE AGAINST WHAT WAS FETCHED, NEVER A MAGIC MINIMUM. The original guard
# was `[ "$n" -lt 20 ]` and the truncated file had exactly 20, so it passed while
# two ranges were missing. A floor cannot detect off-by-two; only an equality
# check against the source can.
n=$(grep -c '^set_real_ip_from' "$TMP" || true)
if [ "$n" -ne "$EXPECTED" ]; then
  echo "REFUSING: wrote $n ranges but Cloudflare published $EXPECTED" >&2
  rm -f "$TMP"; exit 1
fi
mv "$TMP" "$OUT"; chmod 644 "$OUT"
echo "wrote $OUT with $n of $EXPECTED published ranges"
